version: '3'

services:

  redis:
    image: redis:5-alpine3.8
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: always

    couchdb:
      image: couchdb:latest
      hostname: couchdb.server
      environment:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: password
      ports:
        - "5984:5984"