// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package Catalyst.Protocol.Rpc.Node;

public interface AddNodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalyst.Protocol.Rpc.Node.AddNodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
