// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package Catalyst.Protocol.Rpc.Node;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_PingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_PingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_PongResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_PongResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_VersionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_VersionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_VersionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_VersionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_CreateWalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_CreateWalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_CreateWalletResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_CreateWalletResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_ListWalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_ListWalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_ListWalletResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_ListWalletResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_CreateAddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_CreateAddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_CreateAddressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_CreateAddressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetAddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetAddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetAddressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetAddressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_ListAddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_ListAddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_ListAddressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_ListAddressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_ValidateAddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_ValidateAddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_ValidateAddressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_ValidateAddressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_CreateRawTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_CreateRawTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_CreateRawTransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_CreateRawTransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SignRawTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SignRawTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SignRawTransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SignRawTransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_DecodeRawTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_DecodeRawTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_DecodeRawTransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_DecodeRawTransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_BroadcastRawTransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_BroadcastRawTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_BroadcastRawTransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_BroadcastRawTransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SendToRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SendToRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SendToResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SendToResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SendToFromRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SendToFromRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SendToFromResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SendToFromResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SendManyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SendManyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SendManyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SendManyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SendFromManyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SendFromManyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SendFromManyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SendFromManyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_AddNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_AddNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_AddNodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_AddNodeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetPeerListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetPeerListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetPeerInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetPeerInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetConnectionCountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetConnectionCountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetConnectionCountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetConnectionCountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_InfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_InfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SignMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SignMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_SignMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_SignMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_VerifyMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_VerifyMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_VerifyMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_VerifyMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_ServiceStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_ServiceStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocol_Rpc_Node_ServiceStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocol_Rpc_Node_ServiceStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tRpc.proto\022\032Catalyst.Protocol.Rpc.Node\"" +
      "\033\n\013PingRequest\022\014\n\004ping\030\001 \001(\010\"\034\n\014PongResp" +
      "onse\022\014\n\004pong\030\002 \001(\010\"\037\n\016VersionRequest\022\r\n\005" +
      "query\030\001 \001(\010\"\"\n\017VersionResponse\022\017\n\007versio" +
      "n\030\001 \001(\t\"\037\n\016GetInfoRequest\022\r\n\005query\030\001 \001(\010" +
      "\" \n\017GetInfoResponse\022\r\n\005query\030\001 \001(\t\"$\n\023Cr" +
      "eateWalletRequest\022\r\n\005query\030\001 \001(\010\"%\n\024Crea" +
      "teWalletResponse\022\r\n\005query\030\001 \001(\t\"\"\n\021ListW" +
      "alletRequest\022\r\n\005query\030\001 \001(\010\"#\n\022ListWalle" +
      "tResponse\022\r\n\005query\030\001 \001(\t\"%\n\024CreateAddres" +
      "sRequest\022\r\n\005query\030\001 \001(\010\"&\n\025CreateAddress" +
      "Response\022\r\n\005query\030\001 \001(\t\"\"\n\021GetAddressReq" +
      "uest\022\r\n\005query\030\001 \001(\010\"#\n\022GetAddressRespons" +
      "e\022\r\n\005query\030\001 \001(\t\"#\n\022ListAddressRequest\022\r" +
      "\n\005query\030\001 \001(\010\"$\n\023ListAddressResponse\022\r\n\005" +
      "query\030\001 \001(\t\"\'\n\026ValidateAddressRequest\022\r\n" +
      "\005query\030\001 \001(\010\"(\n\027ValidateAddressResponse\022" +
      "\r\n\005query\030\001 \001(\t\"\"\n\021GetBalanceRequest\022\r\n\005q" +
      "uery\030\001 \001(\010\"#\n\022GetBalanceResponse\022\r\n\005quer" +
      "y\030\001 \001(\t\",\n\033CreateRawTransactionRequest\022\r" +
      "\n\005query\030\001 \001(\010\"-\n\034CreateRawTransactionRes" +
      "ponse\022\r\n\005query\030\001 \001(\t\"*\n\031SignRawTransacti" +
      "onRequest\022\r\n\005query\030\001 \001(\010\"+\n\032SignRawTrans" +
      "actionResponse\022\r\n\005query\030\001 \001(\t\",\n\033DecodeR" +
      "awTransactionRequest\022\r\n\005query\030\001 \001(\010\"-\n\034D" +
      "ecodeRawTransactionResponse\022\r\n\005query\030\001 \001" +
      "(\t\"/\n\036BroadcastRawTransactionRequest\022\r\n\005" +
      "query\030\001 \001(\010\"0\n\037BroadcastRawTransactionRe" +
      "sponse\022\r\n\005query\030\001 \001(\t\"\036\n\rSendToRequest\022\r" +
      "\n\005query\030\001 \001(\010\"\037\n\016SendToResponse\022\r\n\005query" +
      "\030\001 \001(\t\"\"\n\021SendToFromRequest\022\r\n\005query\030\001 \001" +
      "(\010\"#\n\022SendToFromResponse\022\r\n\005query\030\001 \001(\t\"" +
      " \n\017SendManyRequest\022\r\n\005query\030\001 \001(\010\"!\n\020Sen" +
      "dManyResponse\022\r\n\005query\030\001 \001(\t\"$\n\023SendFrom" +
      "ManyRequest\022\r\n\005query\030\001 \001(\010\"%\n\024SendFromMa" +
      "nyResponse\022\r\n\005query\030\001 \001(\t\"\037\n\016AddNodeRequ" +
      "est\022\r\n\005query\030\001 \001(\010\" \n\017AddNodeResponse\022\r\n" +
      "\005query\030\001 \001(\t\"#\n\022GetPeerListRequest\022\r\n\005qu" +
      "ery\030\001 \001(\010\"$\n\023GetPeerListResponse\022\r\n\005quer" +
      "y\030\001 \001(\t\"#\n\022GetPeerInfoRequest\022\r\n\005query\030\001" +
      " \001(\010\"$\n\023GetPeerInfoResponse\022\r\n\005query\030\001 \001" +
      "(\t\"*\n\031GetConnectionCountRequest\022\r\n\005query" +
      "\030\001 \001(\010\"+\n\032GetConnectionCountResponse\022\r\n\005" +
      "query\030\001 \001(\t\" \n\017GetDeltaRequest\022\r\n\005query\030" +
      "\001 \001(\010\"!\n\020GetDeltaResponse\022\r\n\005query\030\001 \001(\t" +
      "\"\"\n\021GetMempoolRequest\022\r\n\005query\030\001 \001(\010\"\211\001\n" +
      "\022GetMempoolResponse\022F\n\004info\030\001 \003(\01328.Cata" +
      "lyst.Protocol.Rpc.Node.GetMempoolRespons" +
      "e.InfoEntry\032+\n\tInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\t:\0028\001\"#\n\022SignMessageRequest\022\r" +
      "\n\005query\030\001 \001(\010\"$\n\023SignMessageResponse\022\r\n\005" +
      "query\030\001 \001(\t\"%\n\024VerifyMessageRequest\022\r\n\005q" +
      "uery\030\001 \001(\010\"&\n\025VerifyMessageResponse\022\r\n\005q" +
      "uery\030\001 \001(\t\"%\n\024ServiceStatusRequest\022\r\n\005qu" +
      "ery\030\001 \001(\010\"&\n\025ServiceStatusResponse\022\r\n\005qu" +
      "ery\030\001 \001(\tB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Catalyst_Protocol_Rpc_Node_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Catalyst_Protocol_Rpc_Node_PingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_PingRequest_descriptor,
        new java.lang.String[] { "Ping", });
    internal_static_Catalyst_Protocol_Rpc_Node_PongResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Catalyst_Protocol_Rpc_Node_PongResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_PongResponse_descriptor,
        new java.lang.String[] { "Pong", });
    internal_static_Catalyst_Protocol_Rpc_Node_VersionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Catalyst_Protocol_Rpc_Node_VersionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_VersionRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_VersionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Catalyst_Protocol_Rpc_Node_VersionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_VersionResponse_descriptor,
        new java.lang.String[] { "Version", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Catalyst_Protocol_Rpc_Node_GetInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetInfoRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Catalyst_Protocol_Rpc_Node_GetInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetInfoResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_CreateWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Catalyst_Protocol_Rpc_Node_CreateWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_CreateWalletRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_CreateWalletResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Catalyst_Protocol_Rpc_Node_CreateWalletResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_CreateWalletResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_ListWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Catalyst_Protocol_Rpc_Node_ListWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_ListWalletRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_ListWalletResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Catalyst_Protocol_Rpc_Node_ListWalletResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_ListWalletResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_CreateAddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Catalyst_Protocol_Rpc_Node_CreateAddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_CreateAddressRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_CreateAddressResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Catalyst_Protocol_Rpc_Node_CreateAddressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_CreateAddressResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetAddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Catalyst_Protocol_Rpc_Node_GetAddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetAddressRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetAddressResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Catalyst_Protocol_Rpc_Node_GetAddressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetAddressResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_ListAddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Catalyst_Protocol_Rpc_Node_ListAddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_ListAddressRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_ListAddressResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Catalyst_Protocol_Rpc_Node_ListAddressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_ListAddressResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_ValidateAddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_Catalyst_Protocol_Rpc_Node_ValidateAddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_ValidateAddressRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_ValidateAddressResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Catalyst_Protocol_Rpc_Node_ValidateAddressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_ValidateAddressResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Catalyst_Protocol_Rpc_Node_GetBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetBalanceRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_Catalyst_Protocol_Rpc_Node_GetBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetBalanceResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_CreateRawTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_Catalyst_Protocol_Rpc_Node_CreateRawTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_CreateRawTransactionRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_CreateRawTransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_Catalyst_Protocol_Rpc_Node_CreateRawTransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_CreateRawTransactionResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SignRawTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_Catalyst_Protocol_Rpc_Node_SignRawTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SignRawTransactionRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SignRawTransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_Catalyst_Protocol_Rpc_Node_SignRawTransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SignRawTransactionResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_DecodeRawTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_Catalyst_Protocol_Rpc_Node_DecodeRawTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_DecodeRawTransactionRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_DecodeRawTransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_Catalyst_Protocol_Rpc_Node_DecodeRawTransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_DecodeRawTransactionResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_BroadcastRawTransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_Catalyst_Protocol_Rpc_Node_BroadcastRawTransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_BroadcastRawTransactionRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_BroadcastRawTransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_Catalyst_Protocol_Rpc_Node_BroadcastRawTransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_BroadcastRawTransactionResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SendToRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_Catalyst_Protocol_Rpc_Node_SendToRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SendToRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SendToResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_Catalyst_Protocol_Rpc_Node_SendToResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SendToResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SendToFromRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_Catalyst_Protocol_Rpc_Node_SendToFromRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SendToFromRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SendToFromResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_Catalyst_Protocol_Rpc_Node_SendToFromResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SendToFromResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SendManyRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_Catalyst_Protocol_Rpc_Node_SendManyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SendManyRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SendManyResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_Catalyst_Protocol_Rpc_Node_SendManyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SendManyResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SendFromManyRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_Catalyst_Protocol_Rpc_Node_SendFromManyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SendFromManyRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SendFromManyResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_Catalyst_Protocol_Rpc_Node_SendFromManyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SendFromManyResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_AddNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_Catalyst_Protocol_Rpc_Node_AddNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_AddNodeRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_AddNodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_Catalyst_Protocol_Rpc_Node_AddNodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_AddNodeResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerListRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetPeerListRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerListResponse_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetPeerListResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetPeerInfoRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_Catalyst_Protocol_Rpc_Node_GetPeerInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetPeerInfoResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetConnectionCountRequest_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_Catalyst_Protocol_Rpc_Node_GetConnectionCountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetConnectionCountRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetConnectionCountResponse_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_Catalyst_Protocol_Rpc_Node_GetConnectionCountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetConnectionCountResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaRequest_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaResponse_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetDeltaResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolRequest_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_descriptor,
        new java.lang.String[] { "Info", });
    internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_InfoEntry_descriptor =
      internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_descriptor.getNestedTypes().get(0);
    internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_InfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_GetMempoolResponse_InfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Catalyst_Protocol_Rpc_Node_SignMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_Catalyst_Protocol_Rpc_Node_SignMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SignMessageRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_SignMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_Catalyst_Protocol_Rpc_Node_SignMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_SignMessageResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_VerifyMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_Catalyst_Protocol_Rpc_Node_VerifyMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_VerifyMessageRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_VerifyMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_Catalyst_Protocol_Rpc_Node_VerifyMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_VerifyMessageResponse_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_ServiceStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_Catalyst_Protocol_Rpc_Node_ServiceStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_ServiceStatusRequest_descriptor,
        new java.lang.String[] { "Query", });
    internal_static_Catalyst_Protocol_Rpc_Node_ServiceStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_Catalyst_Protocol_Rpc_Node_ServiceStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocol_Rpc_Node_ServiceStatusResponse_descriptor,
        new java.lang.String[] { "Query", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
