// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package Catalyst.Protocol.Rpc.Node;

public interface SignRawTransactionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalyst.Protocol.Rpc.Node.SignRawTransactionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool query = 1;</code>
   */
  boolean getQuery();
}
