// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rpc.proto

package Catalyst.Protocol.Rpc.Node;

public interface VersionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Catalyst.Protocol.Rpc.Node.VersionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
