### YamlMime:ManagedReference
items:
- uid: Catalyst.Abstractions.Config.IConfigCopier
  commentId: T:Catalyst.Abstractions.Config.IConfigCopier
  id: IConfigCopier
  parent: Catalyst.Abstractions.Config
  children:
  - Catalyst.Abstractions.Config.IConfigCopier.RunConfigStartUp(System.String,Catalyst.Protocol.Network.NetworkType,System.String,System.Boolean,System.String)
  langs:
  - csharp
  - vb
  name: IConfigCopier
  nameWithType: IConfigCopier
  fullName: Catalyst.Abstractions.Config.IConfigCopier
  type: Interface
  source:
    remote:
      path: src/Catalyst.Abstractions/Config/IConfigCopier.cs
      branch: develop
      repo: https://github.com/catalyst-network/Catalyst.Node.git
    id: IConfigCopier
    path: ../src/Catalyst.Abstractions/Config/IConfigCopier.cs
    startLine: 27
  assemblies:
  - Catalyst.Abstractions
  namespace: Catalyst.Abstractions.Config
  syntax:
    content: public interface IConfigCopier
    content.vb: Public Interface IConfigCopier
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Catalyst.Abstractions.Config.IConfigCopier.RunConfigStartUp(System.String,Catalyst.Protocol.Network.NetworkType,System.String,System.Boolean,System.String)
  commentId: M:Catalyst.Abstractions.Config.IConfigCopier.RunConfigStartUp(System.String,Catalyst.Protocol.Network.NetworkType,System.String,System.Boolean,System.String)
  id: RunConfigStartUp(System.String,Catalyst.Protocol.Network.NetworkType,System.String,System.Boolean,System.String)
  parent: Catalyst.Abstractions.Config.IConfigCopier
  langs:
  - csharp
  - vb
  name: RunConfigStartUp(String, NetworkType, String, Boolean, String)
  nameWithType: IConfigCopier.RunConfigStartUp(String, NetworkType, String, Boolean, String)
  fullName: Catalyst.Abstractions.Config.IConfigCopier.RunConfigStartUp(System.String, Catalyst.Protocol.Network.NetworkType, System.String, System.Boolean, System.String)
  type: Method
  source:
    remote:
      path: src/Catalyst.Abstractions/Config/IConfigCopier.cs
      branch: develop
      repo: https://github.com/catalyst-network/Catalyst.Node.git
    id: RunConfigStartUp
    path: ../src/Catalyst.Abstractions/Config/IConfigCopier.cs
    startLine: 38
  assemblies:
  - Catalyst.Abstractions
  namespace: Catalyst.Abstractions.Config
  summary: "\nFinds out which config files are missing from the catalyst home directory and\ncopies them over if needed.\n"
  example: []
  syntax:
    content: void RunConfigStartUp(string dataDir, NetworkType networkType = NetworkType.Devnet, string sourceFolder = null, bool overwrite = false, string overrideNetworkFile = null)
    parameters:
    - id: dataDir
      type: System.String
      description: Home catalyst directory
    - id: networkType
      type: Catalyst.Protocol.Network.NetworkType
      description: Network on which to run the node
    - id: sourceFolder
      type: System.String
      description: ''
    - id: overwrite
      type: System.Boolean
      description: Should config existing config files be overwritten by default?
    - id: overrideNetworkFile
      type: System.String
      description: ''
    content.vb: Sub RunConfigStartUp(dataDir As String, networkType As NetworkType = NetworkType.Devnet, sourceFolder As String = Nothing, overwrite As Boolean = False, overrideNetworkFile As String = Nothing)
  overload: Catalyst.Abstractions.Config.IConfigCopier.RunConfigStartUp*
references:
- uid: Catalyst.Abstractions.Config
  commentId: N:Catalyst.Abstractions.Config
  name: Catalyst.Abstractions.Config
  nameWithType: Catalyst.Abstractions.Config
  fullName: Catalyst.Abstractions.Config
- uid: Catalyst.Abstractions.Config.IConfigCopier.RunConfigStartUp*
  commentId: Overload:Catalyst.Abstractions.Config.IConfigCopier.RunConfigStartUp
  name: RunConfigStartUp
  nameWithType: IConfigCopier.RunConfigStartUp
  fullName: Catalyst.Abstractions.Config.IConfigCopier.RunConfigStartUp
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Catalyst.Protocol.Network.NetworkType
  commentId: T:Catalyst.Protocol.Network.NetworkType
  parent: Catalyst.Protocol.Network
  name: NetworkType
  nameWithType: NetworkType
  fullName: Catalyst.Protocol.Network.NetworkType
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Catalyst.Protocol.Network
  commentId: N:Catalyst.Protocol.Network
  name: Catalyst.Protocol.Network
  nameWithType: Catalyst.Protocol.Network
  fullName: Catalyst.Protocol.Network
