@startuml
class ByteUtil <<static>> {
    + {static} ToByteString(bytes:IEnumerable<byte>) : ByteString
    + {static} GenerateCorrelationId() : ulong
    + {static} CombineByteArrays(arrays:byte[][]) : byte[]
    + {static} AppendByte(array:byte[], b:byte) : byte[]
    + {static} Slice(array:byte[], start:int, end:int) : byte[]
    + {static} InitialiseEmptyByteArray(length:int) : byte[]
    - {static} MergeToEnum(arrays:byte[][]) : IEnumerable<byte>
    + {static} Merge(arrays:byte[][]) : byte[]
    + {static} ByteToString(array:byte[]) : string
}
ByteUtil o-> "Rand" Random
@enduml
