@startuml
class GetMempoolRequestHandler <<sealed>> {
    + GetMempoolRequestHandler(peerIdentifier:IPeerIdentifier, mempool:IMempool, messageCorrelationCache:IMessageCorrelationCache, logger:ILogger)
    # <<override>> Handler(message:IChanneledMessage<AnySigned>) : void
    - GetMempoolContent() : MapField<string, string>
}
class "CorrelatableMessageHandlerBase`2"<T1,T2> {
}
"CorrelatableMessageHandlerBase`2" "<GetMempoolRequest,IMessageCorrelationCache>" <|-- GetMempoolRequestHandler
IRpcRequestHandler <|-- GetMempoolRequestHandler
GetMempoolRequestHandler --> "_mempool" IMempool
GetMempoolRequestHandler --> "_peerId" PeerId
@enduml
