@startuml
class SignMessageRequestHandler <<sealed>> {
    + SignMessageRequestHandler(peerIdentifier:IPeerIdentifier, logger:ILogger, keySigner:IKeySigner, messageCorrelationCache:IMessageCorrelationCache)
    # <<override>> Handler(message:IChanneledMessage<AnySigned>) : void
}
class "CorrelatableMessageHandlerBase`2"<T1,T2> {
}
"CorrelatableMessageHandlerBase`2" "<SignMessageRequest,IMessageCorrelationCache>" <|-- SignMessageRequestHandler
IRpcRequestHandler <|-- SignMessageRequestHandler
SignMessageRequestHandler --> "_keySigner" IKeySigner
SignMessageRequestHandler --> "_peerId" PeerId
@enduml
