@startuml
class KeyStoreServiceWrapped {
    + KeyStoreServiceWrapped()
    + GetAddressFromKeyStore(json:string) : string
    + GenerateUTCFileName(address:string) : string
    + DecryptKeyStoreFromFile(password:string, filePath:string) : byte[]
    + DecryptKeyStoreFromJson(password:string, json:string) : byte[]
    + EncryptAndGenerateDefaultKeyStoreAsJson(password:string, key:byte[], address:string) : string
}
IKeyStoreWrapper <|-- KeyStoreServiceWrapped
KeyStoreServiceWrapped --> "_keyStoreWrapperImplementation" KeyStoreService
@enduml
