@startuml
class LocalKeyStore <<sealed>> {
    + LocalKeyStore(cryptoContext:ICryptoContext, keyStoreService:IKeyStoreWrapper, fileSystem:IFileSystem, logger:ILogger)
    + GetKey(publicKey:IPublicKey, password:string) : IPrivateKey
    + GetKey(fileName:string, password:string) : IPrivateKey
    + StoreKey(privateKey:IPrivateKey, fileName:string, password:string) : bool
}
IKeyStore <|-- LocalKeyStore
LocalKeyStore --> "_cryptoContext" ICryptoContext
LocalKeyStore --> "_keyStoreService" IKeyStoreWrapper
LocalKeyStore --> "_logger" ILogger
LocalKeyStore --> "_fileSystem" IFileSystem
@enduml
