@startuml
class RemoteKeyStore {
    + RemoteKeyStore(cryptoContext:ICryptoContext, keyStoreService:IKeyStoreWrapper, logger:ILogger)
    + GetKey(publicKey:IPublicKey, password:string) : IPrivateKey
    + GetKey(filePath:string, password:string) : IPrivateKey
    + StoreKey(privateKey:IPrivateKey, address:string, password:string) : bool
}
IKeyStore <|-- RemoteKeyStore
RemoteKeyStore --> "_keyStoreService" IKeyStoreWrapper
RemoteKeyStore --> "_logger" ILogger
RemoteKeyStore --> "CryptoContext" ICryptoContext
@enduml
