@startuml
interface "IP2PMessageDto`2"<out TMessage,out TMessageType> {
    Message : TMessage <<get>>
}
class "IMessageDto`1"<T> {
}
"IMessageDto`1" "<TMessageType>" <|-- "IP2PMessageDto`2"
"IP2PMessageDto`2" --> "Recipient" IPEndPoint
@enduml
