@startuml
interface IPeerSettings {
    PayoutAddress : string <<get>>
    PublicKey : string <<get>>
    Announce : bool <<get>>
    MaxConnections : ushort <<get>>
    Port : int <<get>>
    Magic : int <<get>>
    PfxFileName : string <<get>>
    AddressVersion : byte <<get>>
}
class "IList`1"<T> {
}
IPeerSettings --> "AnnounceServer" IPEndPoint
IPeerSettings --> "BindAddress" IPAddress
IPeerSettings --> "EndPoint" IPEndPoint
IPeerSettings --> "KnownNodes<string>" "IList`1"
IPeerSettings --> "SeedServers<string>" "IList`1"
@enduml
