@startuml
class MessageCorrelationCacheTests <<sealed>> {
    + MessageCorrelationCacheTests(output:ITestOutputHelper)
    + TryMatchResponseAsync_should_match_existing_records_with_matching_correlation_id() : void
    + TryMatchResponseAsync_when_matching_should_increase_reputation() : void
    + TryMatchResponseAsync_should_not_match_existing_records_with_non_matching_correlation_id() : void
    + TryMatchResponseAsync_when_not_matching_correlationId_should_not_change_reputation() : void
    + TryMatchResponseAsync_should_not_match_on_wrong_response_type() : void
}
class "IList`1"<T> {
}
class "Dictionary`2"<T1,T2> {
}
MessageCorrelationCacheTests --> "_pendingRequests<PendingRequest>" "IList`1"
MessageCorrelationCacheTests --> "_cache" P2PCorrelationCache
MessageCorrelationCacheTests --> "_reputationByPeerIdentifier<IPeerIdentifier,int>" "Dictionary`2"
@enduml
