// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Peer.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PeerRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PeerRoot : GPBRootObject
@end

#pragma mark - PeerProtocol

@interface PeerProtocol : GPBMessage

@end

#pragma mark - PeerProtocol_PingRequest

typedef GPB_ENUM(PeerProtocol_PingRequest_FieldNumber) {
  PeerProtocol_PingRequest_FieldNumber_Ping = 1,
};

@interface PeerProtocol_PingRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ping;

@end

#pragma mark - PeerProtocol_PongResponse

typedef GPB_ENUM(PeerProtocol_PongResponse_FieldNumber) {
  PeerProtocol_PongResponse_FieldNumber_Pong = 1,
};

@interface PeerProtocol_PongResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *pong;

@end

#pragma mark - PeerProtocol_ACK

typedef GPB_ENUM(PeerProtocol_ACK_FieldNumber) {
  PeerProtocol_ACK_FieldNumber_Ack = 1,
};

@interface PeerProtocol_ACK : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *ack;

@end

#pragma mark - PeerProtocol_NACK

typedef GPB_ENUM(PeerProtocol_NACK_FieldNumber) {
  PeerProtocol_NACK_FieldNumber_Nack = 1,
};

@interface PeerProtocol_NACK : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *nack;

@end

#pragma mark - PeerProtocol_PeerInfoRequest

typedef GPB_ENUM(PeerProtocol_PeerInfoRequest_FieldNumber) {
  PeerProtocol_PeerInfoRequest_FieldNumber_Ping = 1,
};

@interface PeerProtocol_PeerInfoRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ping;

@end

#pragma mark - PeerProtocol_PeerInfoResponse

typedef GPB_ENUM(PeerProtocol_PeerInfoResponse_FieldNumber) {
  PeerProtocol_PeerInfoResponse_FieldNumber_Pong = 1,
};

@interface PeerProtocol_PeerInfoResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *pong;

@end

#pragma mark - PeerProtocol_PeerNeighborsRequest

typedef GPB_ENUM(PeerProtocol_PeerNeighborsRequest_FieldNumber) {
  PeerProtocol_PeerNeighborsRequest_FieldNumber_Ping = 1,
};

@interface PeerProtocol_PeerNeighborsRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ping;

@end

#pragma mark - PeerProtocol_PeerNeighborsResponse

typedef GPB_ENUM(PeerProtocol_PeerNeighborsResponse_FieldNumber) {
  PeerProtocol_PeerNeighborsResponse_FieldNumber_Pong = 1,
};

@interface PeerProtocol_PeerNeighborsResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *pong;

@end

#pragma mark - PeerProtocol_ChallengeRequest

typedef GPB_ENUM(PeerProtocol_ChallengeRequest_FieldNumber) {
  PeerProtocol_ChallengeRequest_FieldNumber_Nonce = 1,
};

@interface PeerProtocol_ChallengeRequest : GPBMessage

@property(nonatomic, readwrite) int64_t nonce;

@end

#pragma mark - PeerProtocol_ChallengeResponse

typedef GPB_ENUM(PeerProtocol_ChallengeResponse_FieldNumber) {
  PeerProtocol_ChallengeResponse_FieldNumber_SignedNonce = 1,
  PeerProtocol_ChallengeResponse_FieldNumber_PublicKey = 2,
};

@interface PeerProtocol_ChallengeResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *signedNonce;

@property(nonatomic, readwrite, copy, null_resettable) NSString *publicKey;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
