// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MempoolBuf.proto

package Catalyst.Protocols.Mempool;

public final class MempoolBuf {
  private MempoolBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Catalyst.Protocols.Mempool.Tx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string addressSource = 1;</code>
     */
    java.lang.String getAddressSource();
    /**
     * <code>string addressSource = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddressSourceBytes();

    /**
     * <code>string addressDest = 2;</code>
     */
    java.lang.String getAddressDest();
    /**
     * <code>string addressDest = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddressDestBytes();

    /**
     * <code>string signature = 3;</code>
     */
    java.lang.String getSignature();
    /**
     * <code>string signature = 3;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>fixed32 amount = 4;</code>
     */
    int getAmount();

    /**
     * <code>fixed32 fee = 5;</code>
     */
    int getFee();

    /**
     * <code>fixed32 outputAmount = 6;</code>
     */
    int getOutputAmount();

    /**
     * <code>string inputAction = 7;</code>
     */
    java.lang.String getInputAction();
    /**
     * <code>string inputAction = 7;</code>
     */
    com.google.protobuf.ByteString
        getInputActionBytes();

    /**
     * <code>string unlockScript = 8;</code>
     */
    java.lang.String getUnlockScript();
    /**
     * <code>string unlockScript = 8;</code>
     */
    com.google.protobuf.ByteString
        getUnlockScriptBytes();

    /**
     * <code>string unlockingProgram = 9;</code>
     */
    java.lang.String getUnlockingProgram();
    /**
     * <code>string unlockingProgram = 9;</code>
     */
    com.google.protobuf.ByteString
        getUnlockingProgramBytes();

    /**
     * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
     */
    boolean hasUpdated();
    /**
     * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
     */
    Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp getUpdated();
    /**
     * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
     */
    Catalyst.Protocols.Mempool.MempoolBuf.Tx.TimestampOrBuilder getUpdatedOrBuilder();
  }
  /**
   * Protobuf type {@code Catalyst.Protocols.Mempool.Tx}
   */
  public  static final class Tx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Catalyst.Protocols.Mempool.Tx)
      TxOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tx.newBuilder() to construct.
    private Tx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tx() {
      addressSource_ = "";
      addressDest_ = "";
      signature_ = "";
      amount_ = 0;
      fee_ = 0;
      outputAmount_ = 0;
      inputAction_ = "";
      unlockScript_ = "";
      unlockingProgram_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              addressSource_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              addressDest_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              signature_ = s;
              break;
            }
            case 37: {

              amount_ = input.readFixed32();
              break;
            }
            case 45: {

              fee_ = input.readFixed32();
              break;
            }
            case 53: {

              outputAmount_ = input.readFixed32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              inputAction_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              unlockScript_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              unlockingProgram_ = s;
              break;
            }
            case 82: {
              Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.Builder subBuilder = null;
              if (updated_ != null) {
                subBuilder = updated_.toBuilder();
              }
              updated_ = input.readMessage(Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(updated_);
                updated_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Tx_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Tx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Catalyst.Protocols.Mempool.MempoolBuf.Tx.class, Catalyst.Protocols.Mempool.MempoolBuf.Tx.Builder.class);
    }

    public interface TimestampOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Catalyst.Protocols.Mempool.Tx.Timestamp)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 seconds = 1;</code>
       */
      long getSeconds();

      /**
       * <code>int32 nanos = 2;</code>
       */
      int getNanos();
    }
    /**
     * Protobuf type {@code Catalyst.Protocols.Mempool.Tx.Timestamp}
     */
    public  static final class Timestamp extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Catalyst.Protocols.Mempool.Tx.Timestamp)
        TimestampOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Timestamp.newBuilder() to construct.
      private Timestamp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Timestamp() {
        seconds_ = 0L;
        nanos_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Timestamp(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                seconds_ = input.readInt64();
                break;
              }
              case 16: {

                nanos_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Tx_Timestamp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Tx_Timestamp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.class, Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.Builder.class);
      }

      public static final int SECONDS_FIELD_NUMBER = 1;
      private long seconds_;
      /**
       * <code>int64 seconds = 1;</code>
       */
      public long getSeconds() {
        return seconds_;
      }

      public static final int NANOS_FIELD_NUMBER = 2;
      private int nanos_;
      /**
       * <code>int32 nanos = 2;</code>
       */
      public int getNanos() {
        return nanos_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (seconds_ != 0L) {
          output.writeInt64(1, seconds_);
        }
        if (nanos_ != 0) {
          output.writeInt32(2, nanos_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (seconds_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, seconds_);
        }
        if (nanos_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, nanos_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp)) {
          return super.equals(obj);
        }
        Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp other = (Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp) obj;

        boolean result = true;
        result = result && (getSeconds()
            == other.getSeconds());
        result = result && (getNanos()
            == other.getNanos());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SECONDS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSeconds());
        hash = (37 * hash) + NANOS_FIELD_NUMBER;
        hash = (53 * hash) + getNanos();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Catalyst.Protocols.Mempool.Tx.Timestamp}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Catalyst.Protocols.Mempool.Tx.Timestamp)
          Catalyst.Protocols.Mempool.MempoolBuf.Tx.TimestampOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Tx_Timestamp_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Tx_Timestamp_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.class, Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.Builder.class);
        }

        // Construct using Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          seconds_ = 0L;

          nanos_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Tx_Timestamp_descriptor;
        }

        @java.lang.Override
        public Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp getDefaultInstanceForType() {
          return Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.getDefaultInstance();
        }

        @java.lang.Override
        public Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp build() {
          Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp buildPartial() {
          Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp result = new Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp(this);
          result.seconds_ = seconds_;
          result.nanos_ = nanos_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp) {
            return mergeFrom((Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp other) {
          if (other == Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.getDefaultInstance()) return this;
          if (other.getSeconds() != 0L) {
            setSeconds(other.getSeconds());
          }
          if (other.getNanos() != 0) {
            setNanos(other.getNanos());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long seconds_ ;
        /**
         * <code>int64 seconds = 1;</code>
         */
        public long getSeconds() {
          return seconds_;
        }
        /**
         * <code>int64 seconds = 1;</code>
         */
        public Builder setSeconds(long value) {
          
          seconds_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 seconds = 1;</code>
         */
        public Builder clearSeconds() {
          
          seconds_ = 0L;
          onChanged();
          return this;
        }

        private int nanos_ ;
        /**
         * <code>int32 nanos = 2;</code>
         */
        public int getNanos() {
          return nanos_;
        }
        /**
         * <code>int32 nanos = 2;</code>
         */
        public Builder setNanos(int value) {
          
          nanos_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 nanos = 2;</code>
         */
        public Builder clearNanos() {
          
          nanos_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Catalyst.Protocols.Mempool.Tx.Timestamp)
      }

      // @@protoc_insertion_point(class_scope:Catalyst.Protocols.Mempool.Tx.Timestamp)
      private static final Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp();
      }

      public static Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Timestamp>
          PARSER = new com.google.protobuf.AbstractParser<Timestamp>() {
        @java.lang.Override
        public Timestamp parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Timestamp(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Timestamp> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Timestamp> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ADDRESSSOURCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object addressSource_;
    /**
     * <code>string addressSource = 1;</code>
     */
    public java.lang.String getAddressSource() {
      java.lang.Object ref = addressSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addressSource_ = s;
        return s;
      }
    }
    /**
     * <code>string addressSource = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressSourceBytes() {
      java.lang.Object ref = addressSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addressSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESSDEST_FIELD_NUMBER = 2;
    private volatile java.lang.Object addressDest_;
    /**
     * <code>string addressDest = 2;</code>
     */
    public java.lang.String getAddressDest() {
      java.lang.Object ref = addressDest_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addressDest_ = s;
        return s;
      }
    }
    /**
     * <code>string addressDest = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressDestBytes() {
      java.lang.Object ref = addressDest_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addressDest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 3;
    private volatile java.lang.Object signature_;
    /**
     * <code>string signature = 3;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      }
    }
    /**
     * <code>string signature = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private int amount_;
    /**
     * <code>fixed32 amount = 4;</code>
     */
    public int getAmount() {
      return amount_;
    }

    public static final int FEE_FIELD_NUMBER = 5;
    private int fee_;
    /**
     * <code>fixed32 fee = 5;</code>
     */
    public int getFee() {
      return fee_;
    }

    public static final int OUTPUTAMOUNT_FIELD_NUMBER = 6;
    private int outputAmount_;
    /**
     * <code>fixed32 outputAmount = 6;</code>
     */
    public int getOutputAmount() {
      return outputAmount_;
    }

    public static final int INPUTACTION_FIELD_NUMBER = 7;
    private volatile java.lang.Object inputAction_;
    /**
     * <code>string inputAction = 7;</code>
     */
    public java.lang.String getInputAction() {
      java.lang.Object ref = inputAction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inputAction_ = s;
        return s;
      }
    }
    /**
     * <code>string inputAction = 7;</code>
     */
    public com.google.protobuf.ByteString
        getInputActionBytes() {
      java.lang.Object ref = inputAction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inputAction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNLOCKSCRIPT_FIELD_NUMBER = 8;
    private volatile java.lang.Object unlockScript_;
    /**
     * <code>string unlockScript = 8;</code>
     */
    public java.lang.String getUnlockScript() {
      java.lang.Object ref = unlockScript_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unlockScript_ = s;
        return s;
      }
    }
    /**
     * <code>string unlockScript = 8;</code>
     */
    public com.google.protobuf.ByteString
        getUnlockScriptBytes() {
      java.lang.Object ref = unlockScript_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unlockScript_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNLOCKINGPROGRAM_FIELD_NUMBER = 9;
    private volatile java.lang.Object unlockingProgram_;
    /**
     * <code>string unlockingProgram = 9;</code>
     */
    public java.lang.String getUnlockingProgram() {
      java.lang.Object ref = unlockingProgram_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unlockingProgram_ = s;
        return s;
      }
    }
    /**
     * <code>string unlockingProgram = 9;</code>
     */
    public com.google.protobuf.ByteString
        getUnlockingProgramBytes() {
      java.lang.Object ref = unlockingProgram_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unlockingProgram_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATED_FIELD_NUMBER = 10;
    private Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp updated_;
    /**
     * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
     */
    public boolean hasUpdated() {
      return updated_ != null;
    }
    /**
     * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
     */
    public Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp getUpdated() {
      return updated_ == null ? Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.getDefaultInstance() : updated_;
    }
    /**
     * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
     */
    public Catalyst.Protocols.Mempool.MempoolBuf.Tx.TimestampOrBuilder getUpdatedOrBuilder() {
      return getUpdated();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addressSource_);
      }
      if (!getAddressDestBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addressDest_);
      }
      if (!getSignatureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, signature_);
      }
      if (amount_ != 0) {
        output.writeFixed32(4, amount_);
      }
      if (fee_ != 0) {
        output.writeFixed32(5, fee_);
      }
      if (outputAmount_ != 0) {
        output.writeFixed32(6, outputAmount_);
      }
      if (!getInputActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, inputAction_);
      }
      if (!getUnlockScriptBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, unlockScript_);
      }
      if (!getUnlockingProgramBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, unlockingProgram_);
      }
      if (updated_ != null) {
        output.writeMessage(10, getUpdated());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addressSource_);
      }
      if (!getAddressDestBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, addressDest_);
      }
      if (!getSignatureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, signature_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, amount_);
      }
      if (fee_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(5, fee_);
      }
      if (outputAmount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(6, outputAmount_);
      }
      if (!getInputActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, inputAction_);
      }
      if (!getUnlockScriptBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, unlockScript_);
      }
      if (!getUnlockingProgramBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, unlockingProgram_);
      }
      if (updated_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getUpdated());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Catalyst.Protocols.Mempool.MempoolBuf.Tx)) {
        return super.equals(obj);
      }
      Catalyst.Protocols.Mempool.MempoolBuf.Tx other = (Catalyst.Protocols.Mempool.MempoolBuf.Tx) obj;

      boolean result = true;
      result = result && getAddressSource()
          .equals(other.getAddressSource());
      result = result && getAddressDest()
          .equals(other.getAddressDest());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && (getAmount()
          == other.getAmount());
      result = result && (getFee()
          == other.getFee());
      result = result && (getOutputAmount()
          == other.getOutputAmount());
      result = result && getInputAction()
          .equals(other.getInputAction());
      result = result && getUnlockScript()
          .equals(other.getUnlockScript());
      result = result && getUnlockingProgram()
          .equals(other.getUnlockingProgram());
      result = result && (hasUpdated() == other.hasUpdated());
      if (hasUpdated()) {
        result = result && getUpdated()
            .equals(other.getUpdated());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESSSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getAddressSource().hashCode();
      hash = (37 * hash) + ADDRESSDEST_FIELD_NUMBER;
      hash = (53 * hash) + getAddressDest().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (37 * hash) + FEE_FIELD_NUMBER;
      hash = (53 * hash) + getFee();
      hash = (37 * hash) + OUTPUTAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getOutputAmount();
      hash = (37 * hash) + INPUTACTION_FIELD_NUMBER;
      hash = (53 * hash) + getInputAction().hashCode();
      hash = (37 * hash) + UNLOCKSCRIPT_FIELD_NUMBER;
      hash = (53 * hash) + getUnlockScript().hashCode();
      hash = (37 * hash) + UNLOCKINGPROGRAM_FIELD_NUMBER;
      hash = (53 * hash) + getUnlockingProgram().hashCode();
      if (hasUpdated()) {
        hash = (37 * hash) + UPDATED_FIELD_NUMBER;
        hash = (53 * hash) + getUpdated().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Catalyst.Protocols.Mempool.MempoolBuf.Tx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Catalyst.Protocols.Mempool.Tx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Catalyst.Protocols.Mempool.Tx)
        Catalyst.Protocols.Mempool.MempoolBuf.TxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Tx_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Tx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Catalyst.Protocols.Mempool.MempoolBuf.Tx.class, Catalyst.Protocols.Mempool.MempoolBuf.Tx.Builder.class);
      }

      // Construct using Catalyst.Protocols.Mempool.MempoolBuf.Tx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        addressSource_ = "";

        addressDest_ = "";

        signature_ = "";

        amount_ = 0;

        fee_ = 0;

        outputAmount_ = 0;

        inputAction_ = "";

        unlockScript_ = "";

        unlockingProgram_ = "";

        if (updatedBuilder_ == null) {
          updated_ = null;
        } else {
          updated_ = null;
          updatedBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Tx_descriptor;
      }

      @java.lang.Override
      public Catalyst.Protocols.Mempool.MempoolBuf.Tx getDefaultInstanceForType() {
        return Catalyst.Protocols.Mempool.MempoolBuf.Tx.getDefaultInstance();
      }

      @java.lang.Override
      public Catalyst.Protocols.Mempool.MempoolBuf.Tx build() {
        Catalyst.Protocols.Mempool.MempoolBuf.Tx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Catalyst.Protocols.Mempool.MempoolBuf.Tx buildPartial() {
        Catalyst.Protocols.Mempool.MempoolBuf.Tx result = new Catalyst.Protocols.Mempool.MempoolBuf.Tx(this);
        result.addressSource_ = addressSource_;
        result.addressDest_ = addressDest_;
        result.signature_ = signature_;
        result.amount_ = amount_;
        result.fee_ = fee_;
        result.outputAmount_ = outputAmount_;
        result.inputAction_ = inputAction_;
        result.unlockScript_ = unlockScript_;
        result.unlockingProgram_ = unlockingProgram_;
        if (updatedBuilder_ == null) {
          result.updated_ = updated_;
        } else {
          result.updated_ = updatedBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Catalyst.Protocols.Mempool.MempoolBuf.Tx) {
          return mergeFrom((Catalyst.Protocols.Mempool.MempoolBuf.Tx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Catalyst.Protocols.Mempool.MempoolBuf.Tx other) {
        if (other == Catalyst.Protocols.Mempool.MempoolBuf.Tx.getDefaultInstance()) return this;
        if (!other.getAddressSource().isEmpty()) {
          addressSource_ = other.addressSource_;
          onChanged();
        }
        if (!other.getAddressDest().isEmpty()) {
          addressDest_ = other.addressDest_;
          onChanged();
        }
        if (!other.getSignature().isEmpty()) {
          signature_ = other.signature_;
          onChanged();
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        if (other.getFee() != 0) {
          setFee(other.getFee());
        }
        if (other.getOutputAmount() != 0) {
          setOutputAmount(other.getOutputAmount());
        }
        if (!other.getInputAction().isEmpty()) {
          inputAction_ = other.inputAction_;
          onChanged();
        }
        if (!other.getUnlockScript().isEmpty()) {
          unlockScript_ = other.unlockScript_;
          onChanged();
        }
        if (!other.getUnlockingProgram().isEmpty()) {
          unlockingProgram_ = other.unlockingProgram_;
          onChanged();
        }
        if (other.hasUpdated()) {
          mergeUpdated(other.getUpdated());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Catalyst.Protocols.Mempool.MempoolBuf.Tx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Catalyst.Protocols.Mempool.MempoolBuf.Tx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object addressSource_ = "";
      /**
       * <code>string addressSource = 1;</code>
       */
      public java.lang.String getAddressSource() {
        java.lang.Object ref = addressSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addressSource_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string addressSource = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressSourceBytes() {
        java.lang.Object ref = addressSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addressSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string addressSource = 1;</code>
       */
      public Builder setAddressSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addressSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string addressSource = 1;</code>
       */
      public Builder clearAddressSource() {
        
        addressSource_ = getDefaultInstance().getAddressSource();
        onChanged();
        return this;
      }
      /**
       * <code>string addressSource = 1;</code>
       */
      public Builder setAddressSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addressSource_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object addressDest_ = "";
      /**
       * <code>string addressDest = 2;</code>
       */
      public java.lang.String getAddressDest() {
        java.lang.Object ref = addressDest_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addressDest_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string addressDest = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressDestBytes() {
        java.lang.Object ref = addressDest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addressDest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string addressDest = 2;</code>
       */
      public Builder setAddressDest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addressDest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string addressDest = 2;</code>
       */
      public Builder clearAddressDest() {
        
        addressDest_ = getDefaultInstance().getAddressDest();
        onChanged();
        return this;
      }
      /**
       * <code>string addressDest = 2;</code>
       */
      public Builder setAddressDestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addressDest_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <code>string signature = 3;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string signature = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string signature = 3;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 3;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 3;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signature_ = value;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>fixed32 amount = 4;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>fixed32 amount = 4;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 amount = 4;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }

      private int fee_ ;
      /**
       * <code>fixed32 fee = 5;</code>
       */
      public int getFee() {
        return fee_;
      }
      /**
       * <code>fixed32 fee = 5;</code>
       */
      public Builder setFee(int value) {
        
        fee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 fee = 5;</code>
       */
      public Builder clearFee() {
        
        fee_ = 0;
        onChanged();
        return this;
      }

      private int outputAmount_ ;
      /**
       * <code>fixed32 outputAmount = 6;</code>
       */
      public int getOutputAmount() {
        return outputAmount_;
      }
      /**
       * <code>fixed32 outputAmount = 6;</code>
       */
      public Builder setOutputAmount(int value) {
        
        outputAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 outputAmount = 6;</code>
       */
      public Builder clearOutputAmount() {
        
        outputAmount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object inputAction_ = "";
      /**
       * <code>string inputAction = 7;</code>
       */
      public java.lang.String getInputAction() {
        java.lang.Object ref = inputAction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          inputAction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string inputAction = 7;</code>
       */
      public com.google.protobuf.ByteString
          getInputActionBytes() {
        java.lang.Object ref = inputAction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          inputAction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string inputAction = 7;</code>
       */
      public Builder setInputAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        inputAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string inputAction = 7;</code>
       */
      public Builder clearInputAction() {
        
        inputAction_ = getDefaultInstance().getInputAction();
        onChanged();
        return this;
      }
      /**
       * <code>string inputAction = 7;</code>
       */
      public Builder setInputActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        inputAction_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object unlockScript_ = "";
      /**
       * <code>string unlockScript = 8;</code>
       */
      public java.lang.String getUnlockScript() {
        java.lang.Object ref = unlockScript_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unlockScript_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unlockScript = 8;</code>
       */
      public com.google.protobuf.ByteString
          getUnlockScriptBytes() {
        java.lang.Object ref = unlockScript_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unlockScript_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unlockScript = 8;</code>
       */
      public Builder setUnlockScript(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        unlockScript_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string unlockScript = 8;</code>
       */
      public Builder clearUnlockScript() {
        
        unlockScript_ = getDefaultInstance().getUnlockScript();
        onChanged();
        return this;
      }
      /**
       * <code>string unlockScript = 8;</code>
       */
      public Builder setUnlockScriptBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        unlockScript_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object unlockingProgram_ = "";
      /**
       * <code>string unlockingProgram = 9;</code>
       */
      public java.lang.String getUnlockingProgram() {
        java.lang.Object ref = unlockingProgram_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unlockingProgram_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unlockingProgram = 9;</code>
       */
      public com.google.protobuf.ByteString
          getUnlockingProgramBytes() {
        java.lang.Object ref = unlockingProgram_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unlockingProgram_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unlockingProgram = 9;</code>
       */
      public Builder setUnlockingProgram(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        unlockingProgram_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string unlockingProgram = 9;</code>
       */
      public Builder clearUnlockingProgram() {
        
        unlockingProgram_ = getDefaultInstance().getUnlockingProgram();
        onChanged();
        return this;
      }
      /**
       * <code>string unlockingProgram = 9;</code>
       */
      public Builder setUnlockingProgramBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        unlockingProgram_ = value;
        onChanged();
        return this;
      }

      private Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp updated_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp, Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.Builder, Catalyst.Protocols.Mempool.MempoolBuf.Tx.TimestampOrBuilder> updatedBuilder_;
      /**
       * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
       */
      public boolean hasUpdated() {
        return updatedBuilder_ != null || updated_ != null;
      }
      /**
       * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
       */
      public Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp getUpdated() {
        if (updatedBuilder_ == null) {
          return updated_ == null ? Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.getDefaultInstance() : updated_;
        } else {
          return updatedBuilder_.getMessage();
        }
      }
      /**
       * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
       */
      public Builder setUpdated(Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp value) {
        if (updatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updated_ = value;
          onChanged();
        } else {
          updatedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
       */
      public Builder setUpdated(
          Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.Builder builderForValue) {
        if (updatedBuilder_ == null) {
          updated_ = builderForValue.build();
          onChanged();
        } else {
          updatedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
       */
      public Builder mergeUpdated(Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp value) {
        if (updatedBuilder_ == null) {
          if (updated_ != null) {
            updated_ =
              Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.newBuilder(updated_).mergeFrom(value).buildPartial();
          } else {
            updated_ = value;
          }
          onChanged();
        } else {
          updatedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
       */
      public Builder clearUpdated() {
        if (updatedBuilder_ == null) {
          updated_ = null;
          onChanged();
        } else {
          updated_ = null;
          updatedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
       */
      public Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.Builder getUpdatedBuilder() {
        
        onChanged();
        return getUpdatedFieldBuilder().getBuilder();
      }
      /**
       * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
       */
      public Catalyst.Protocols.Mempool.MempoolBuf.Tx.TimestampOrBuilder getUpdatedOrBuilder() {
        if (updatedBuilder_ != null) {
          return updatedBuilder_.getMessageOrBuilder();
        } else {
          return updated_ == null ?
              Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.getDefaultInstance() : updated_;
        }
      }
      /**
       * <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp, Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.Builder, Catalyst.Protocols.Mempool.MempoolBuf.Tx.TimestampOrBuilder> 
          getUpdatedFieldBuilder() {
        if (updatedBuilder_ == null) {
          updatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp, Catalyst.Protocols.Mempool.MempoolBuf.Tx.Timestamp.Builder, Catalyst.Protocols.Mempool.MempoolBuf.Tx.TimestampOrBuilder>(
                  getUpdated(),
                  getParentForChildren(),
                  isClean());
          updated_ = null;
        }
        return updatedBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Catalyst.Protocols.Mempool.Tx)
    }

    // @@protoc_insertion_point(class_scope:Catalyst.Protocols.Mempool.Tx)
    private static final Catalyst.Protocols.Mempool.MempoolBuf.Tx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Catalyst.Protocols.Mempool.MempoolBuf.Tx();
    }

    public static Catalyst.Protocols.Mempool.MempoolBuf.Tx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tx>
        PARSER = new com.google.protobuf.AbstractParser<Tx>() {
      @java.lang.Override
      public Tx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tx> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Catalyst.Protocols.Mempool.MempoolBuf.Tx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Catalyst.Protocols.Mempool.Key)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string hashed_signature = 1;</code>
     */
    java.lang.String getHashedSignature();
    /**
     * <code>string hashed_signature = 1;</code>
     */
    com.google.protobuf.ByteString
        getHashedSignatureBytes();
  }
  /**
   * Protobuf type {@code Catalyst.Protocols.Mempool.Key}
   */
  public  static final class Key extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Catalyst.Protocols.Mempool.Key)
      KeyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Key.newBuilder() to construct.
    private Key(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Key() {
      hashedSignature_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Key(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              hashedSignature_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Key_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Key_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Catalyst.Protocols.Mempool.MempoolBuf.Key.class, Catalyst.Protocols.Mempool.MempoolBuf.Key.Builder.class);
    }

    public static final int HASHED_SIGNATURE_FIELD_NUMBER = 1;
    private volatile java.lang.Object hashedSignature_;
    /**
     * <code>string hashed_signature = 1;</code>
     */
    public java.lang.String getHashedSignature() {
      java.lang.Object ref = hashedSignature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hashedSignature_ = s;
        return s;
      }
    }
    /**
     * <code>string hashed_signature = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHashedSignatureBytes() {
      java.lang.Object ref = hashedSignature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashedSignature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHashedSignatureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hashedSignature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHashedSignatureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hashedSignature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Catalyst.Protocols.Mempool.MempoolBuf.Key)) {
        return super.equals(obj);
      }
      Catalyst.Protocols.Mempool.MempoolBuf.Key other = (Catalyst.Protocols.Mempool.MempoolBuf.Key) obj;

      boolean result = true;
      result = result && getHashedSignature()
          .equals(other.getHashedSignature());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HASHED_SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getHashedSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Catalyst.Protocols.Mempool.MempoolBuf.Key parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Catalyst.Protocols.Mempool.MempoolBuf.Key prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Catalyst.Protocols.Mempool.Key}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Catalyst.Protocols.Mempool.Key)
        Catalyst.Protocols.Mempool.MempoolBuf.KeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Key_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Key_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Catalyst.Protocols.Mempool.MempoolBuf.Key.class, Catalyst.Protocols.Mempool.MempoolBuf.Key.Builder.class);
      }

      // Construct using Catalyst.Protocols.Mempool.MempoolBuf.Key.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hashedSignature_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Catalyst.Protocols.Mempool.MempoolBuf.internal_static_Catalyst_Protocols_Mempool_Key_descriptor;
      }

      @java.lang.Override
      public Catalyst.Protocols.Mempool.MempoolBuf.Key getDefaultInstanceForType() {
        return Catalyst.Protocols.Mempool.MempoolBuf.Key.getDefaultInstance();
      }

      @java.lang.Override
      public Catalyst.Protocols.Mempool.MempoolBuf.Key build() {
        Catalyst.Protocols.Mempool.MempoolBuf.Key result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Catalyst.Protocols.Mempool.MempoolBuf.Key buildPartial() {
        Catalyst.Protocols.Mempool.MempoolBuf.Key result = new Catalyst.Protocols.Mempool.MempoolBuf.Key(this);
        result.hashedSignature_ = hashedSignature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Catalyst.Protocols.Mempool.MempoolBuf.Key) {
          return mergeFrom((Catalyst.Protocols.Mempool.MempoolBuf.Key)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Catalyst.Protocols.Mempool.MempoolBuf.Key other) {
        if (other == Catalyst.Protocols.Mempool.MempoolBuf.Key.getDefaultInstance()) return this;
        if (!other.getHashedSignature().isEmpty()) {
          hashedSignature_ = other.hashedSignature_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Catalyst.Protocols.Mempool.MempoolBuf.Key parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Catalyst.Protocols.Mempool.MempoolBuf.Key) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object hashedSignature_ = "";
      /**
       * <code>string hashed_signature = 1;</code>
       */
      public java.lang.String getHashedSignature() {
        java.lang.Object ref = hashedSignature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hashedSignature_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hashed_signature = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHashedSignatureBytes() {
        java.lang.Object ref = hashedSignature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hashedSignature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hashed_signature = 1;</code>
       */
      public Builder setHashedSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hashedSignature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hashed_signature = 1;</code>
       */
      public Builder clearHashedSignature() {
        
        hashedSignature_ = getDefaultInstance().getHashedSignature();
        onChanged();
        return this;
      }
      /**
       * <code>string hashed_signature = 1;</code>
       */
      public Builder setHashedSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hashedSignature_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Catalyst.Protocols.Mempool.Key)
    }

    // @@protoc_insertion_point(class_scope:Catalyst.Protocols.Mempool.Key)
    private static final Catalyst.Protocols.Mempool.MempoolBuf.Key DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Catalyst.Protocols.Mempool.MempoolBuf.Key();
    }

    public static Catalyst.Protocols.Mempool.MempoolBuf.Key getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Key>
        PARSER = new com.google.protobuf.AbstractParser<Key>() {
      @java.lang.Override
      public Key parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Key(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Key> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Key> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Catalyst.Protocols.Mempool.MempoolBuf.Key getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocols_Mempool_Tx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocols_Mempool_Tx_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocols_Mempool_Tx_Timestamp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocols_Mempool_Tx_Timestamp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Catalyst_Protocols_Mempool_Key_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Catalyst_Protocols_Mempool_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MempoolBuf.proto\022\032Catalyst.Protocols.M" +
      "empool\"\243\002\n\002Tx\022\025\n\raddressSource\030\001 \001(\t\022\023\n\013" +
      "addressDest\030\002 \001(\t\022\021\n\tsignature\030\003 \001(\t\022\016\n\006" +
      "amount\030\004 \001(\007\022\013\n\003fee\030\005 \001(\007\022\024\n\014outputAmoun" +
      "t\030\006 \001(\007\022\023\n\013inputAction\030\007 \001(\t\022\024\n\014unlockSc" +
      "ript\030\010 \001(\t\022\030\n\020unlockingProgram\030\t \001(\t\0229\n\007" +
      "updated\030\n \001(\0132(.Catalyst.Protocols.Mempo" +
      "ol.Tx.Timestamp\032+\n\tTimestamp\022\017\n\007seconds\030" +
      "\001 \001(\003\022\r\n\005nanos\030\002 \001(\005\"\037\n\003Key\022\030\n\020hashed_si" +
      "gnature\030\001 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Catalyst_Protocols_Mempool_Tx_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Catalyst_Protocols_Mempool_Tx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocols_Mempool_Tx_descriptor,
        new java.lang.String[] { "AddressSource", "AddressDest", "Signature", "Amount", "Fee", "OutputAmount", "InputAction", "UnlockScript", "UnlockingProgram", "Updated", });
    internal_static_Catalyst_Protocols_Mempool_Tx_Timestamp_descriptor =
      internal_static_Catalyst_Protocols_Mempool_Tx_descriptor.getNestedTypes().get(0);
    internal_static_Catalyst_Protocols_Mempool_Tx_Timestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocols_Mempool_Tx_Timestamp_descriptor,
        new java.lang.String[] { "Seconds", "Nanos", });
    internal_static_Catalyst_Protocols_Mempool_Key_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Catalyst_Protocols_Mempool_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Catalyst_Protocols_Mempool_Key_descriptor,
        new java.lang.String[] { "HashedSignature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
