@startuml
class LocalKeyStoreTests {
    - <<readonly>> _fileName : string
    - <<readonly>> _password : string
    + LocalKeyStoreTests(output:ITestOutputHelper)
    + TestStoreAndRetrieveKey() : void
    + TestWrongPasswordStoreAndRetrieveKey() : void
}
class CustomNethereumException {
    + CustomNethereumException(message:string)
}
FileSystemBasedTest <|-- LocalKeyStoreTests
LocalKeyStoreTests --> "_keystore" IKeyStore
LocalKeyStoreTests --> "_context" ICryptoContext
LocalKeyStoreTests --> "_keyStoreService" IKeyStoreWrapper
LocalKeyStoreTests --> "_privateKey" NSecPrivateKeyWrapper
LocalKeyStoreTests +-- CustomNethereumException
Exception <|-- CustomNethereumException
@enduml
