@startuml
class ConfigFileBasedTest {
    # ConfigFileBasedTest(output:ITestOutputHelper)
    # LogOutputTemplate : string <<get>> <<set>> = "{Timestamp:HH:mm:ss} [{Level:u3}] ({ThreadId}) {Message} ({SourceContext}){NewLine}{Exception}"
    # <<virtual>> ConfigureContainerBuilder(config:IConfigurationRoot, writeLogsToTestOutput:bool, writeLogsToFile:bool) : void
    - ConfigureLogging(config:IConfigurationRoot, writeLogsToTestOutput:bool, writeLogsToFile:bool) : void
}
FileSystemBasedTest <|-- ConfigFileBasedTest
ConfigFileBasedTest --> "ContainerBuilder" ContainerBuilder
ConfigFileBasedTest o-> "LogEventLevel" LogEventLevel
@enduml
