@startuml
abstract class FileSystemBasedTest {
    # <<readonly>> CurrentTestName : string
    # FileSystemBasedTest(output:ITestOutputHelper)
    + Dispose() : void
    # <<virtual>> Dispose(disposing:bool) : void
    - {static} TryDeleteFolder(d:DirectoryInfo) : void
}
IDisposable <|-- FileSystemBasedTest
FileSystemBasedTest --> "CurrentTest" ITest
FileSystemBasedTest --> "FileSystem" IFileSystem
FileSystemBasedTest --> "Output" ITestOutputHelper
FileSystemBasedTest --> "_testDirectory" DirectoryInfo
@enduml
