@startuml
class PeerIdentifierHelper <<static>> {
    + {static} GetPeerIdentifier(publicKeySeed:string, clientId:string, clientVersion:int, ipAddress:IPAddress, port:int) : IPeerIdentifier
}
@enduml
