@startuml
class TestPasswordReader <<sealed>> {
    - <<readonly>> _expectedPassword : string
    + TestPasswordReader(expectedPassword:string)
    + {static} BuildSecureStringPassword(expectedPassword:string) : SecureString
    + ReadSecurePassword(passwordContext:string) : SecureString
}
IPasswordReader <|-- TestPasswordReader
@enduml
