stages:
    - build
    - test

build_dotnet:
    image: microsoft/dotnet:latest

    before_script:
        - "cd src"
        - "dotnet restore"

    build:
        stage: build
        script:
            - "dotnet build"

    test:
        stage: test
        script: 
            - "ls ./**/UnitTests/*.csproj | dotnet test"

build_docker:
    image: docker:stable
    
    services:
        - docker:dind

    build:
        stage: build
        script:
            - "docker build ."
