stages:
    - build
    - test

dotnet_build:
    image: microsoft/dotnet:latest
    before_script:
        - "cd src"
        - "dotnet restore"
    stage: build
    script:
        - "dotnet build"

dotnet_test:
    stage: test
    script: 
        - "ls ./**/UnitTests/*.csproj | dotnet test"

build_docker:
    image: docker:stable
    services:
        - docker:dind
    stage: build
    script:
        - "docker build ."
