version: '3'

networks:
  devNet:
    ipam:
      config:
        - subnet: 172.36.0.0/24
          
services:

  seedDns:
    image: samuelcolvin/dnserver
    networks:
      devNet:
        ipv4_address: 172.36.0.101    
    ports:
      - "53/udp"
    volumes:
      - ./devnet_dnszone.txt:/zones/zones.txt
      
  node-1:
    stdin_open: true
    tty: true    
    hostname: node-1
    image: catalyst.network/catalyst.node:latest
    networks:
      devNet:
        ipv4_address: 172.36.0.110
  
  node-2:
    stdin_open: true
    tty: true    
    hostname: node-2
    image: catalyst.network/catalyst.node:latest
    networks:
      devNet:
        ipv4_address: 172.36.0.120
  
  node-3:
    stdin_open: true
    tty: true
    hostname: node-3
    image: catalyst.network/catalyst.node:latest
    networks:
      devNet:
        ipv4_address: 172.36.0.130

  node-4:
    stdin_open: true
    tty: true    
    hostname: node-4
    image: catalyst.network/catalyst.node:latest
    networks:
      devNet:
        ipv4_address: 172.36.0.140              