steps:
  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packDirectory: '$(Build.ArtifactStagingDirectory)/packages/pre-releases'
      arguments: '--configuration=$(BuildConfiguration) --output=$(Build.ArtifactStagingDirectory) --version-suffix=$(Build.BuildId)$(release.type) --include-source --include-symbols'
      packagesToPack: $(PROJECT)
      nobuild: true
      failOnStandardError: 'true'
    timeoutInMinutes: 10

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/packages/pre-releases'
      ArtifactName: $(PACKAGE_NAME)
      failOnStandardError: 'true'
    timeoutInMinutes: 10
    condition: succeededOrFailed()

  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: 'NuGet'
      failOnStandardError: 'true'
    timeoutInMinutes: 10