version: '3.4'

# This is an example docker-compose file for IPFS Cluster
# It runs two Cluster peers (cluster0, cluster1) attached to two
# IPFS daemons (ipfs0, ipfs1).
#
# It expects a ".ipfsData" subfolder as follows where it will store configurations
# and states permanently:
#
# .ipfsData/
# |-- cluster0
# |-- cluster1
# |-- ipfs0
# |-- ipfs1
#
# 
# During the first start, default configurations are created for all peers.

services:

  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:release
    ports:
          - "4001:4001" # ipfs swarm
          - "4002:4002/udp" # udp swarm
          - "5001:5001" # expose if needed/wanted
          - "8080:8080" # exposes if needed/wanted
    volumes:
      - ./.ipfsData/ipfs0:/data/ipfs
      
  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_SECRET: adc72159e1ce63351c13de6a5e4d3b2f511232a771cb8c3e7829fc514d89d119 
      IPFS_API: /dns4/ipfs0/tcp/5001
    ports:
          - "9094:9094" # API
          - "9096:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./.ipfsData/cluster0:/data/ipfs-cluster
      
  ipfs1:
    container_name: ipfs1
    image: ipfs/go-ipfs:release
    ports:
          - "4101:4001" # ipfs swarm
          - "4102:4002/udp" # udp swarm
          - "5101:5001" # expose if needed/wanted
          - "8180:8080" # exposes if needed/wanted
    volumes:
      - ./.ipfsData/ipfs1:/data/ipfs

  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - cluster0
      - ipfs1
    environment:
      CLUSTER_SECRET: adc72159e1ce63351c13de6a5e4d3b2f511232a771cb8c3e7829fc514d89d119
      IPFS_API: /dns4/ipfs1/tcp/5001
    ports:
          - "9194:9094" # API
          - "9196:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./.ipfsData/cluster1:/data/ipfs-cluster
    entrypoint:
      - "/sbin/tini"
      - "--"
    command: >-
      sh -c '
        cmd="daemon --upgrade"
        if [ ! -d /data/ipfs-cluster/raft ]; then
          while ! ipfs-cluster-ctl --host /dns4/cluster0/tcp/9094 id; do
            sleep 1
          done
          pid=`ipfs-cluster-ctl --host /dns4/cluster0/tcp/9094 id | grep -o -E "^(\w+)"`
          sleep 10
          cmd="daemon --bootstrap /dns4/cluster0/tcp/9096/ipfs/$$pid"
        fi
        /usr/local/bin/entrypoint.sh $$cmd
      '
