version: '3'

networks:
  testNetOverlay:

services:
  redis-mempool:
    image: redis:5-alpine3.8
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: always
    networks:
      - testNetOverlay

  catalyst:
    image: adlnode.azurecr.io/catalyst:testnet
    ports:
      - "42069:42069"
    restart: always
    networks:
      - testNetOverlay
    volumes:
      - "/home/nsh/.Atlas"
    depends_on:
      - redis-mempool