version: '3'

networks:
  testNetOverlay:

services:
  redis-mempool:
    image: redis:5-alpine3.8
    volumes:
      - ./data/redis:/data
    restart: always
    networks:
      - testNetOverlay

  catalyst:
    image: adlnode.azurecr.io/catalyst:testnet
    restart: always
    networks:
      - testNetOverlay
    volumes:
      - "/home/nsh/.Catalyst"
    depends_on:
      - redis-mempool
