<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MempoolBuf.proto

namespace Catalyst\Protocols\Mempool;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Catalyst.Protocols.Mempool.Tx</code>
 */
class Tx extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string addressSource = 1;</code>
     */
    private $addressSource = '';
    /**
     * Generated from protobuf field <code>string addressDest = 2;</code>
     */
    private $addressDest = '';
    /**
     * Generated from protobuf field <code>string signature = 3;</code>
     */
    private $signature = '';
    /**
     * Generated from protobuf field <code>fixed32 amount = 4;</code>
     */
    private $amount = 0;
    /**
     * Generated from protobuf field <code>fixed32 fee = 5;</code>
     */
    private $fee = 0;
    /**
     * Generated from protobuf field <code>fixed32 outputAmount = 6;</code>
     */
    private $outputAmount = 0;
    /**
     * Generated from protobuf field <code>string inputAction = 7;</code>
     */
    private $inputAction = '';
    /**
     * Generated from protobuf field <code>string unlockScript = 8;</code>
     */
    private $unlockScript = '';
    /**
     * Generated from protobuf field <code>string unlockingProgram = 9;</code>
     */
    private $unlockingProgram = '';
    /**
     * Generated from protobuf field <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
     */
    private $updated = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $addressSource
     *     @type string $addressDest
     *     @type string $signature
     *     @type int $amount
     *     @type int $fee
     *     @type int $outputAmount
     *     @type string $inputAction
     *     @type string $unlockScript
     *     @type string $unlockingProgram
     *     @type \Catalyst\Protocols\Mempool\Tx\Timestamp $updated
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\MempoolBuf::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string addressSource = 1;</code>
     * @return string
     */
    public function getAddressSource()
    {
        return $this->addressSource;
    }

    /**
     * Generated from protobuf field <code>string addressSource = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->addressSource = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string addressDest = 2;</code>
     * @return string
     */
    public function getAddressDest()
    {
        return $this->addressDest;
    }

    /**
     * Generated from protobuf field <code>string addressDest = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddressDest($var)
    {
        GPBUtil::checkString($var, True);
        $this->addressDest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signature = 3;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>string signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 amount = 4;</code>
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>fixed32 amount = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 fee = 5;</code>
     * @return int
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>fixed32 fee = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkUint32($var);
        $this->fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed32 outputAmount = 6;</code>
     * @return int
     */
    public function getOutputAmount()
    {
        return $this->outputAmount;
    }

    /**
     * Generated from protobuf field <code>fixed32 outputAmount = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setOutputAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->outputAmount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string inputAction = 7;</code>
     * @return string
     */
    public function getInputAction()
    {
        return $this->inputAction;
    }

    /**
     * Generated from protobuf field <code>string inputAction = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setInputAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->inputAction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unlockScript = 8;</code>
     * @return string
     */
    public function getUnlockScript()
    {
        return $this->unlockScript;
    }

    /**
     * Generated from protobuf field <code>string unlockScript = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUnlockScript($var)
    {
        GPBUtil::checkString($var, True);
        $this->unlockScript = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unlockingProgram = 9;</code>
     * @return string
     */
    public function getUnlockingProgram()
    {
        return $this->unlockingProgram;
    }

    /**
     * Generated from protobuf field <code>string unlockingProgram = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUnlockingProgram($var)
    {
        GPBUtil::checkString($var, True);
        $this->unlockingProgram = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
     * @return \Catalyst\Protocols\Mempool\Tx\Timestamp
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Generated from protobuf field <code>.Catalyst.Protocols.Mempool.Tx.Timestamp updated = 10;</code>
     * @param \Catalyst\Protocols\Mempool\Tx\Timestamp $var
     * @return $this
     */
    public function setUpdated($var)
    {
        GPBUtil::checkMessage($var, \Catalyst\Protocols\Mempool\Tx_Timestamp::class);
        $this->updated = $var;

        return $this;
    }

}

