<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MempoolBuf.proto

namespace Catalyst\Protocols\Mempool;

if (false) {
    /**
     * This class is deprecated. Use Catalyst\Protocols\Mempool\Tx\Timestamp instead.
     * @deprecated
     */
    class Tx_Timestamp {}
}
class_exists(Tx\Timestamp::class);
@trigger_error('Catalyst\Protocols\Mempool\Tx_Timestamp is deprecated and will be removed in the next major release. Use Catalyst\Protocols\Mempool\Tx\Timestamp instead', E_USER_DEPRECATED);

