@startuml
abstract class "AbstractServer`1"<T> {
    # <<const>> BackLogValue : int = 100
    # <<internal>> AbstractServer(logger:ILogger)
    + <<async>> StartServer(listenAddress:IPAddress, port:int) : Task<AbstractServer<T>>
}
class "AbstractIo`1"<T> {
}
"AbstractIo`1" "<T>" <|-- "AbstractServer`1"
"AbstractServer`1" --> "Server" IServerBootstrp
@enduml
