@startuml
abstract class "AbstractServer`2"<ST,BT> {
    # Server : BT <<get>> <<set>>
    # <<internal>> AbstractServer(logger:ILogger)
    + <<virtual>> <<async>> StartServer(listenAddress:IPAddress, port:int) : Task<AbstractServer<ST, BT>>
}
class "AbstractIo`2"<T1,T2> {
}
"AbstractIo`2" "<ST,BT>" <|-- "AbstractServer`2"
@enduml
