@startuml
class "InboundChannelInitializer`1"<T> <<sealed>> {
    + InboundChannelInitializer(initializationAction:Action<T>, encoder:IChannelHandler, decoder:IChannelHandler, channelHandler:IChannelHandler, certificate:X509Certificate)
    + InboundChannelInitializer(initializationAction:Action<T>, encoder:IChannelHandler, decoder:IChannelHandler, channelHandler:IChannelHandler)
    # <<override>> InitChannel(channel:T) : void
    + <<override>> ToString() : string
}
class "AbstractChannelInitializer`1"<T> {
}
"AbstractChannelInitializer`1" "<T>" <|-- "InboundChannelInitializer`1"
@enduml
