@startuml
class TcpServer <<sealed>> {
    + TcpServer(logger:ILogger)
    + Bootstrap(channelInitializer:IChannelHandler) : TcpServer
    + <<override>> <<async>> Shutdown() : Task
    + <<override>> ToString() : string
}
class "AbstractServer`1"<T> {
}
"AbstractServer`1" "<ISocketServer>" <|-- TcpServer
TcpServer --> "_supervisorEventLoop" IEventLoopGroup
@enduml
