@startuml
class TcpServer <<sealed>> {
    + TcpServer(logger:ILogger)
    + Bootstrap(channelInitializer:IChannelHandler) : TcpServer
    + <<override>> <<async>> Shutdown() : Task
}
class "AbstractServer`2"<T1,T2> {
}
"AbstractServer`2" "<ISocketServer,IServerBootstrap>" <|-- TcpServer
TcpServer --> "_supervisorEventLoop" IEventLoopGroup
@enduml
