@startuml
class UdpServer <<sealed>> {
    + UdpServer(logger:ILogger)
    + Bootstrap(channelInitializer:IChannelHandler) : UdpServer
    + <<override>> <<async>> StartServer(listenAddress:IPAddress, port:int) : Task<AbstractServer<ISocketServer, IBootstrap>>
}
class "AbstractServer`2"<T1,T2> {
}
"AbstractServer`2" "<ISocketServer,IBootstrap>" <|-- UdpServer
UdpServer --> "Server" Bootstrap
@enduml
