@startuml
class "UdpServer`1"<T> <<sealed>> {
    + UdpServer(logger:ILogger)
    + Bootstrap(channelInitializer:IChannelHandler) : UdpServer<T>
    + <<override>> ToString() : string
}
class "AbstractServer`1"<T> {
}
"AbstractServer`1" "<ISocketServer>" <|-- "UdpServer`1"
@enduml
