@startuml
class SocketClientRegistryTests <<sealed>> {
    + Can_init_tcp_client_registry() : void
    + Can_init_udp_client_registry() : void
    + Can_init_peer_client_registry() : void
    + Can_init_rcp_client_registry() : void
    + Socket_Registry_Has_A_List() : void
    + Cannot_Add_Inactive_Client() : void
    - {static} GetSubstituteForActiveSocketClient() : ISocketClient
    + Can_Add_Socket_To_Registry_And_Get_Same_Client_From_HashCode() : void
    + Can_Add_Multiple_Sockets_To_Registry() : void
    + Can_Add_Multiple_Sockets_To_Registry_And_Get_One() : void
    + Can_Remove_Socket_From_Registry() : void
    + Can_Add_Multiple_Sockets_To_Registry_And_Remove_One() : void
}
@enduml
