@startuml
class Network {
    - Network(id:int, name:string)
}
class DevNet <<sealed>> {
    + DevNet()
}
class TestNet <<sealed>> {
    + TestNet()
}
class MainNet <<sealed>> {
    + MainNet()
}
Enumeration <|-- Network
Network o-> "Main" Network
Network o-> "Test" Network
Network o-> "Dev" Network
Network +-- DevNet
Network <|-- DevNet
Network +-- TestNet
Network <|-- TestNet
Network +-- MainNet
Network <|-- MainNet
@enduml
