@startuml
class P2PMessages {
    - P2PMessages(id:int, name:string)
}
class PingRequestMessage <<sealed>> {
    + PingRequestMessage()
}
class PingResponseMessage <<sealed>> {
    + PingResponseMessage()
}
class GetNeighbourRequestMessage <<sealed>> {
    + GetNeighbourRequestMessage()
}
class GetNeighbourResponseMessage <<sealed>> {
    + GetNeighbourResponseMessage()
}
class BroadcastTransactionMessage <<sealed>> {
    + BroadcastTransactionMessage()
}
Enumeration <|-- P2PMessages
IEnumerableMessageType <|-- P2PMessages
P2PMessages o-> "PingRequest" P2PMessages
P2PMessages o-> "PingResponse" P2PMessages
P2PMessages o-> "GetNeighbourRequest" P2PMessages
P2PMessages o-> "GetNeighbourResponse" P2PMessages
P2PMessages o-> "BroadcastTransaction" P2PMessages
P2PMessages +-- PingRequestMessage
P2PMessages <|-- PingRequestMessage
P2PMessages +-- PingResponseMessage
P2PMessages <|-- PingResponseMessage
P2PMessages +-- GetNeighbourRequestMessage
P2PMessages <|-- GetNeighbourRequestMessage
P2PMessages +-- GetNeighbourResponseMessage
P2PMessages <|-- GetNeighbourResponseMessage
P2PMessages +-- BroadcastTransactionMessage
P2PMessages <|-- BroadcastTransactionMessage
@enduml
