@startuml
class GetMempoolResponseHandler <<sealed>> {
    + GetMempoolResponseHandler(output:IUserOutput, messageCorrelationCache:IMessageCorrelationCache, logger:ILogger)
    # <<override>> Handler(message:IChanneledMessage<AnySigned>) : void
}
class "CorrelatableMessageHandlerBase`2"<T1,T2> {
}
"CorrelatableMessageHandlerBase`2" "<GetMempoolResponse,IMessageCorrelationCache>" <|-- GetMempoolResponseHandler
IRpcResponseHandler <|-- GetMempoolResponseHandler
GetMempoolResponseHandler --> "_output" IUserOutput
@enduml
