@startuml
class VerifyMessageResponseHandler <<sealed>> {
    + VerifyMessageResponseHandler(output:IUserOutput, messageCorrelationCache:IMessageCorrelationCache, logger:ILogger)
    # <<override>> Handler(message:IChanneledMessage<AnySigned>) : void
}
class "CorrelatableMessageHandlerBase`2"<T1,T2> {
}
"CorrelatableMessageHandlerBase`2" "<VerifyMessageResponse,IMessageCorrelationCache>" <|-- VerifyMessageResponseHandler
IRpcResponseHandler <|-- VerifyMessageResponseHandler
VerifyMessageResponseHandler --> "_output" IUserOutput
@enduml
