@startuml
class NodeRpcServer {
    + NodeRpcServer(settings:IRpcServerSettings, logger:ILogger, certificateStore:ICertificateStore, requestHandlers:IEnumerable<IRpcRequestHandler>)
    # <<override>> Dispose(disposing:bool) : void
}
class "IObservable`1"<T> {
}
TcpServer <|-- NodeRpcServer
INodeRpcServer <|-- NodeRpcServer
NodeRpcServer --> "_cancellationSource" CancellationTokenSource
NodeRpcServer --> "_certificate" X509Certificate2
NodeRpcServer --> "Settings" IRpcServerSettings
NodeRpcServer --> "MessageStream<IChanneledMessage<AnySigned>>" "IObservable`1"
@enduml
