@startuml
class RpcServerSettings {
    + RpcServerSettings(rootSection:IConfigurationRoot)
    + Port : int <<get>>
    + PfxFileName : string <<get>>
    + MutualAuthentication : bool <<get>>
    + AcceptInvalidCerts : bool <<get>>
}
IRpcServerSettings <|-- RpcServerSettings
RpcServerSettings --> "NodeConfig" IConfigurationRoot
RpcServerSettings --> "BindAddress" IPAddress
@enduml
