@startuml
interface IConnection {
    Connected : bool <<set>> <<get>>
    Disposed : bool <<get>> <<set>>
    IsConnected() : bool
}
IDisposable <|-- IConnection
IConnection --> "TcpClient" TcpClient
IConnection --> "EndPoint" IPEndPoint
IConnection --> "SslStream" SslStream
@enduml
