@startuml
interface IKeyStore {
    GetKey(publicKey:IPublicKey, password:string) : IPrivateKey
    GetKey(filePath:string, password:string) : IPrivateKey
    StoreKey(privateKey:IPrivateKey, address:string, password:string) : bool
}
@enduml
