@startuml
interface IP2P {
    FindNode(queryingNode:IPeerIdentifier, targetNode:IPeerIdentifier) : List<IPeerIdentifier>
    GetPeers(queryingNode:IPeerIdentifier) : List<IPeerIdentifier>
    Store(k:string, v:byte[]) : bool
    FindValue(k:string) : dynamic
    PeerExchange(queryingNode:IPeerIdentifier) : List<IPeerIdentifier>
}
IP2P --> "Discovery" IPeerDiscovery
IP2P --> "Identifier" IPeerIdentifier
IP2P --> "Settings" IPeerSettings
IP2P --> "Messaging" IP2PMessaging
@enduml
