@startuml
interface ISocketClient {
    ConnectClient(listenAddress:IPAddress, port:int) : Task<ISocketClient>
    ShutdownClient() : Task
}
ISocketClient --> "Channel" IChannel
ISocketClient --> "Client" IBootstrap
@enduml
