@startuml
interface ISocketClient {
    ConnectClient(listenAddress:IPAddress, port:int) : Task<ISocketClient>
}
IISocket <|-- ISocketClient
ISocketClient --> "Channel" IChannel
ISocketClient --> "Client" IBootstrap
@enduml
