// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Rpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ADL.Rpc.Proto.Service {
  public static partial class RpcService
  {
    static readonly string __ServiceName = "ADL.Rpc.Proto.Service.RpcService";

    static readonly grpc::Marshaller<global::ADL.Rpc.Proto.Service.PingRequest> __Marshaller_ADL_Rpc_Proto_Service_PingRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ADL.Rpc.Proto.Service.PingRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ADL.Rpc.Proto.Service.PongResponse> __Marshaller_ADL_Rpc_Proto_Service_PongResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ADL.Rpc.Proto.Service.PongResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::ADL.Rpc.Proto.Service.PingRequest, global::ADL.Rpc.Proto.Service.PongResponse> __Method_Greeting = new grpc::Method<global::ADL.Rpc.Proto.Service.PingRequest, global::ADL.Rpc.Proto.Service.PongResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Greeting",
        __Marshaller_ADL_Rpc_Proto_Service_PingRequest,
        __Marshaller_ADL_Rpc_Proto_Service_PongResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ADL.Rpc.Proto.Service.RpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RpcService</summary>
    public abstract partial class RpcServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ADL.Rpc.Proto.Service.PongResponse> Greeting(global::ADL.Rpc.Proto.Service.PingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RpcService</summary>
    public partial class RpcServiceClient : grpc::ClientBase<RpcServiceClient>
    {
      /// <summary>Creates a new client for RpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RpcServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ADL.Rpc.Proto.Service.PongResponse Greeting(global::ADL.Rpc.Proto.Service.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Greeting(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ADL.Rpc.Proto.Service.PongResponse Greeting(global::ADL.Rpc.Proto.Service.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Greeting, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ADL.Rpc.Proto.Service.PongResponse> GreetingAsync(global::ADL.Rpc.Proto.Service.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GreetingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ADL.Rpc.Proto.Service.PongResponse> GreetingAsync(global::ADL.Rpc.Proto.Service.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Greeting, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RpcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RpcServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Greeting, serviceImpl.Greeting).Build();
    }

  }
}
#endregion
