@startuml
class ProtobufExtensions <<static>> {
    - <<const>> CatalystProtocol : string = "Catalyst.Protocol"
    - {static} <<readonly>> RequestSuffix : string = "Request"
    - {static} <<readonly>> ResponseSuffix : string = "Response"
    + {static} ShortenedFullName(descriptor:MessageDescriptor) : string
    + {static} ShortenedProtoFullName(protoType:Type) : string
    + {static} ToAnySigned(protobufObject:T, senderId:PeerId, correlationId:Guid) : AnySigned
    + {static} FromAnySigned(message:AnySigned) : IMessage
    + {static} FromAnySigned(message:AnySigned) : T
    + {static} ToUtf8ByteString(utf8String:string) : ByteString
    + {static} ToGuid(guidBytes:ByteString) : Guid
    + {static} ToByteString(guid:Guid) : ByteString
    + {static} GetRequestType(responseTypeUrl:string) : string
    + {static} GetResponseType(requestTypeUrl:string) : string
    - {static} SwapSuffixes(requestTypeUrl:string, originalSuffix:string, targetSuffix:string) : string
}
class "Dictionary`2"<T1,T2> {
}
ProtobufExtensions o-> "ProtoToClrNameMapper<string,string>" "Dictionary`2"
@enduml
