<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peer.proto

namespace Catalyst\Protocol\Peer;

if (false) {
    /**
     * This class is deprecated. Use Catalyst\Protocol\Peer\PeerProtocol\NACK instead.
     * @deprecated
     */
    class PeerProtocol_NACK {}
}
class_exists(PeerProtocol\NACK::class);
@trigger_error('Catalyst\Protocol\Peer\PeerProtocol_NACK is deprecated and will be removed in the next major release. Use Catalyst\Protocol\Peer\PeerProtocol\NACK instead', E_USER_DEPRECATED);

