<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peer.proto

namespace Catalyst\Protocol\Peer;

if (false) {
    /**
     * This class is deprecated. Use Catalyst\Protocol\Peer\PeerProtocol\PeerInfoResponse instead.
     * @deprecated
     */
    class PeerProtocol_PeerInfoResponse {}
}
class_exists(PeerProtocol\PeerInfoResponse::class);
@trigger_error('Catalyst\Protocol\Peer\PeerProtocol_PeerInfoResponse is deprecated and will be removed in the next major release. Use Catalyst\Protocol\Peer\PeerProtocol\PeerInfoResponse instead', E_USER_DEPRECATED);

