<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peer.proto

namespace Catalyst\Protocol\Peer;

if (false) {
    /**
     * This class is deprecated. Use Catalyst\Protocol\Peer\PeerProtocol\ChallengeResponse instead.
     * @deprecated
     */
    class PeerProtocol_ChallengeResponse {}
}
class_exists(PeerProtocol\ChallengeResponse::class);
@trigger_error('Catalyst\Protocol\Peer\PeerProtocol_ChallengeResponse is deprecated and will be removed in the next major release. Use Catalyst\Protocol\Peer\PeerProtocol\ChallengeResponse instead', E_USER_DEPRECATED);

