<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peer.proto

namespace Catalyst\Protocol\Peer;

if (false) {
    /**
     * This class is deprecated. Use Catalyst\Protocol\Peer\PeerProtocol\PingRequest instead.
     * @deprecated
     */
    class PeerProtocol_PingRequest {}
}
class_exists(PeerProtocol\PingRequest::class);
@trigger_error('Catalyst\Protocol\Peer\PeerProtocol_PingRequest is deprecated and will be removed in the next major release. Use Catalyst\Protocol\Peer\PeerProtocol\PingRequest instead', E_USER_DEPRECATED);

