<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peer.proto

namespace Catalyst\Protocol\Peer;

if (false) {
    /**
     * This class is deprecated. Use Catalyst\Protocol\Peer\PeerProtocol\ChallengeRequest instead.
     * @deprecated
     */
    class PeerProtocol_ChallengeRequest {}
}
class_exists(PeerProtocol\ChallengeRequest::class);
@trigger_error('Catalyst\Protocol\Peer\PeerProtocol_ChallengeRequest is deprecated and will be removed in the next major release. Use Catalyst\Protocol\Peer\PeerProtocol\ChallengeRequest instead', E_USER_DEPRECATED);

