<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peer.proto

namespace Catalyst\Protocol\Peer;

if (false) {
    /**
     * This class is deprecated. Use Catalyst\Protocol\Peer\PeerProtocol\PongResponse instead.
     * @deprecated
     */
    class PeerProtocol_PongResponse {}
}
class_exists(PeerProtocol\PongResponse::class);
@trigger_error('Catalyst\Protocol\Peer\PeerProtocol_PongResponse is deprecated and will be removed in the next major release. Use Catalyst\Protocol\Peer\PeerProtocol\PongResponse instead', E_USER_DEPRECATED);

