<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peer.proto

namespace Catalyst\Protocol\Peer;

if (false) {
    /**
     * This class is deprecated. Use Catalyst\Protocol\Peer\PeerProtocol\PeerInfoRequest instead.
     * @deprecated
     */
    class PeerProtocol_PeerInfoRequest {}
}
class_exists(PeerProtocol\PeerInfoRequest::class);
@trigger_error('Catalyst\Protocol\Peer\PeerProtocol_PeerInfoRequest is deprecated and will be removed in the next major release. Use Catalyst\Protocol\Peer\PeerProtocol\PeerInfoRequest instead', E_USER_DEPRECATED);

