<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peer.proto

namespace Catalyst\Protocol\Peer;

if (false) {
    /**
     * This class is deprecated. Use Catalyst\Protocol\Peer\PeerProtocol\PeerNeighborsResponse instead.
     * @deprecated
     */
    class PeerProtocol_PeerNeighborsResponse {}
}
class_exists(PeerProtocol\PeerNeighborsResponse::class);
@trigger_error('Catalyst\Protocol\Peer\PeerProtocol_PeerNeighborsResponse is deprecated and will be removed in the next major release. Use Catalyst\Protocol\Peer\PeerProtocol\PeerNeighborsResponse instead', E_USER_DEPRECATED);

