<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Peer.proto

namespace Catalyst\Protocol\Peer;

if (false) {
    /**
     * This class is deprecated. Use Catalyst\Protocol\Peer\PeerProtocol\PeerNeighborsRequest instead.
     * @deprecated
     */
    class PeerProtocol_PeerNeighborsRequest {}
}
class_exists(PeerProtocol\PeerNeighborsRequest::class);
@trigger_error('Catalyst\Protocol\Peer\PeerProtocol_PeerNeighborsRequest is deprecated and will be removed in the next major release. Use Catalyst\Protocol\Peer\PeerProtocol\PeerNeighborsRequest instead', E_USER_DEPRECATED);

