@startuml
abstract class ShellBase {
    # ShellBase()
    - Prompt : string <<get>>
    - ServiceName : string <<get>>
    + {abstract} OnStart(args:string[]) : bool
    + {abstract} OnStartWork(args:string[]) : bool
    + {abstract} OnStop(args:string[]) : bool
    + {abstract} OnStopNode(args:string[]) : bool
    + {abstract} OnStopWork(args:string[]) : bool
    # OnHelpCommand(advancedCmds:string) : bool
    + <<virtual>> OnCommand(args:string[]) : bool
    - OnGetCommand(args:string[]) : bool
    # {abstract} OnGetConfig(args:Object) : bool
    # {abstract} OnGetVersion(args:Object) : bool
    # {abstract} OnGetMempool(args:Object) : bool
    + RunConsole() : bool
    + {abstract} ParseCommand(args:string[]) : bool
    # {static} CommandNotFound(args:string[]) : bool
    + {abstract} OnVerifyMessage(opts:object) : bool
}
IShell <|-- ShellBase
ShellBase --> "AppCulture" CultureInfo
@enduml
