@startuml
!include .\/Catalyst.Cli/Program.puml
!include .\/Catalyst.Cli.UnitTests/Program.UnitTests.puml
!include .\/Catalyst.Node.Core/CataystNode.puml
!include .\/Catalyst.Node.Core/Program.puml
!include .\/Catalyst.Node.Core.UnitTests/TestUtils/BaseModuleConfigTest.puml
!include .\/Catalyst.Node.Core.UnitTests/TestUtils/TestPasswordReader.puml
!include .\/Catalyst.Node.Core.UnitTests/TestUtils/ConfigFileBasedTest.puml
!include .\/Catalyst.Node.Core.UnitTests/Modules/JsonConfiguredModuleTest.puml
!include .\/Catalyst.Node.Core.UnitTests/Config/ConfigCopierTests.puml
!include .\/Catalyst.Node.Core.UnitTests/Config/ConfigTests.puml
!include .\/Catalyst.Node.Common.UnitTests/TestUtils/Traits.puml
!include .\/Catalyst.Node.Common.UnitTests/TestUtils/FileSystemBasedTest.puml
!include .\/Catalyst.Node.Common.UnitTests/P2P/NetworkTests.puml
!include .\/Catalyst.Node.Common.UnitTests/Modules/ModuleNamesTests.puml
!include .\/Catalyst.Node.Common/Interfaces/IConnection.puml
!include .\/Catalyst.Node.Common/Interfaces/IP2P.puml
!include .\/Catalyst.Node.Common/Interfaces/IDns.puml
!include .\/Catalyst.Node.Common/Interfaces/IBootstrap.puml
!include .\/Catalyst.Node.Common/Interfaces/IAds.puml
!include .\/Catalyst.Node.Common/Interfaces/IFileSystem.puml
!include .\/Catalyst.Node.Common/Interfaces/ICatalystNode.puml
!include .\/Catalyst.Node.Common/Interfaces/IPeerIdentifier.puml
!include .\/Catalyst.Node.Common/Interfaces/ICertificateStore.puml
!include .\/Catalyst.Node.Common/Interfaces/ISocketServer.puml
!include .\/Catalyst.Node.Common/Interfaces/IServerBootstrap.puml
!include .\/Catalyst.Node.Common/Interfaces/IPeerSettings.puml
!include .\/Catalyst.Node.Common/Interfaces/ICryptoContext.puml
!include .\/Catalyst.Node.Common/Interfaces/IPrivateKey.puml
!include .\/Catalyst.Node.Common/Interfaces/ISocketClient.puml
!include .\/Catalyst.Node.Common/Interfaces/IPublicKey.puml
!include .\/Catalyst.Node.Common/Interfaces/IPeerDiscovery.puml
!include .\/Catalyst.Node.Common/Interfaces/IISocket.puml
!include .\/Catalyst.Node.Common/Interfaces/IKeyValueStore.puml
!include .\/Catalyst.Node.Common/Interfaces/IShell.puml
!include .\/Catalyst.Node.Common/Interfaces/IKeystore.puml
!include .\/Catalyst.Node.Common/Interfaces/IP2PMessaging.puml
!include .\/Catalyst.Node.Common/Interfaces/IMessageSender.puml
!include .\/Catalyst.Node.Common/Interfaces/IPasswordReader.puml
!include .\/Catalyst.Node.Common/Modules/ModuleNames.puml
!include .\/Catalyst.Node.Core/Events/AnnounceNodeEventArgs.puml
!include .\/Catalyst.Node.Core/P2P/PeerIdentifier.puml
!include .\/Catalyst.Node.Core/P2P/P2PService.puml
!include .\/Catalyst.Node.Core/P2P/PeerDiscovery.puml
!include .\/Catalyst.Node.Core/P2P/PeerSettings.puml
!include .\/Catalyst.Node.Core/P2P/Peer.puml
!include .\/Catalyst.Node.Core/Modules/JsonConfiguredModule.puml
!include .\/Catalyst.Node.Core.UnitTests/P2P/Messaging/PeersCanChat.puml
!include .\/Catalyst.Node.Core.UnitTests/Helpers/Redis/RedisConnectorTests.puml
!include .\/Catalyst.Node.Core.UnitTests/Modules/Mempool/MempoolIntegrationTests.puml
!include .\/Catalyst.Node.Core.UnitTests/Modules/Mempool/MempoolTests.puml
!include .\/Catalyst.Node.Common.UnitTests/Helpers/Network/DnsUnitTests.puml
!include .\/Catalyst.Node.Common.UnitTests/Helpers/Network/IpTests.puml
!include .\/Catalyst.Node.Common.UnitTests/Helpers/Keystore/LocalKeyStoreTests.puml
!include .\/Catalyst.Node.Common.UnitTests/Helpers/Cryptography/CertificateStoreTests.puml
!include .\/Catalyst.Node.Common.UnitTests/Helpers/Cryptography/CryptographyTests.puml
!include .\/Catalyst.Node.Common/Helpers/IO/Bootstrap.puml
!include .\/Catalyst.Node.Common/Helpers/IO/AbstractChannelInitializer.puml
!include .\/Catalyst.Node.Common/Helpers/IO/AbstractIO.puml
!include .\/Catalyst.Node.Common/Helpers/IO/ServerBootstrap.puml
!include .\/Catalyst.Node.Common/Helpers/Events/Events.puml
!include .\/Catalyst.Node.Common/Helpers/Shell/Shell.puml
!include .\/Catalyst.Node.Common/Helpers/Shell/ShellBase.puml
!include .\/Catalyst.Node.Common/Helpers/Network/EndpointBuilder.puml
!include .\/Catalyst.Node.Common/Helpers/Network/Dns.puml
!include .\/Catalyst.Node.Common/Helpers/Network/Ip.puml
!include .\/Catalyst.Node.Common/Helpers/FileSystem/FileSystem.puml
!include .\/Catalyst.Node.Common/Helpers/Keystore/KeyStoreServiceWrapped.puml
!include .\/Catalyst.Node.Common/Helpers/Keystore/RemoteKeyStore.puml
!include .\/Catalyst.Node.Common/Helpers/Keystore/LocalKeyStore.puml
!include .\/Catalyst.Node.Common/Helpers/Keystore/IKeyStoreWrapper.puml
!include .\/Catalyst.Node.Common/Helpers/Cryptography/CertificateStore.puml
!include .\/Catalyst.Node.Common/Helpers/Cryptography/NSecCryptoContext.puml
!include .\/Catalyst.Node.Common/Helpers/Cryptography/Signature.puml
!include .\/Catalyst.Node.Common/Helpers/Cryptography/ConsolePasswordReader.puml
!include .\/Catalyst.Node.Common/Helpers/Cryptography/NSecPrivateKeyWrapper.puml
!include .\/Catalyst.Node.Common/Helpers/Cryptography/NSecPublicKeyWrapper.puml
!include .\/Catalyst.Node.Common/Helpers/Enumerator/Enumeration.puml
!include .\/Catalyst.Node.Common/Helpers/Util/StringUtil.puml
!include .\/Catalyst.Node.Common/Helpers/Util/ByteUtil.puml
!include .\/Catalyst.Node.Common/Helpers/Util/DateTimeUtil.puml
!include .\/Catalyst.Node.Common/Helpers/Config/Network.puml
!include .\/Catalyst.Node.Common/Helpers/Config/ConfigCopier.puml
!include .\/Catalyst.Node.Common/Helpers/Config/Constants.puml
!include .\/Catalyst.Node.Common/Modules/KeySigner/KeySigner.puml
!include .\/Catalyst.Node.Core/Components/Redis/RedisConnector.puml
!include .\/Catalyst.Node.Core/Components/Redis/IRedisConnector.puml
!include .\/Catalyst.Node.Core/Components/Redis/RedisStore.puml
!include .\/Catalyst.Node.Core/Components/Redis/IRedisStore.puml
!include .\/Catalyst.Node.Core/P2P/Messaging/SecureTcpMessageClientHandler.puml
!include .\/Catalyst.Node.Core/P2P/Messaging/SecureTcpMessageServerHandler.puml
!include .\/Catalyst.Node.Core/P2P/Messaging/P2PMessaging.puml
!include .\/Catalyst.Node.Core/Modules/Ledger/Ledger.puml
!include .\/Catalyst.Node.Core/Modules/Consensus/Consensus.puml
!include .\/Catalyst.Node.Core/Modules/Dfs/Dfs.puml
!include .\/Catalyst.Node.Core/Modules/Mempool/Mempool.puml
!include .\/Catalyst.Node.Core/Modules/Mempool/StTxModel.puml
!include .\/Catalyst.Node.Core/Modules/Contract/Contract.puml
!include .\/Catalyst.Cli/obj/Debug/netcoreapp2.1/Catalyst.Cli.AssemblyInfo.puml
!include .\/Catalyst.Cli/obj/Debug/netcoreapp2.2/Catalyst.Cli.AssemblyInfo.puml
!include .\/Catalyst.Cli.UnitTests/obj/Debug/netcoreapp2.1/Catalyst.Cli.UnitTests.AssemblyInfo.puml
!include .\/Catalyst.Cli.UnitTests/obj/Debug/netcoreapp2.1/Catalyst.Cli.UnitTests.Program.puml
!include .\/Catalyst.Cli.UnitTests/obj/Debug/netcoreapp2.2/Catalyst.Cli.UnitTests.AssemblyInfo.puml
!include .\/Catalyst.Cli.UnitTests/obj/Debug/netcoreapp2.2/Catalyst.Cli.UnitTests.Program.puml
!include .\/Catalyst.Node.Core.UnitTests/obj/Debug/netcoreapp2.1/Catalyst.Node.Core.UnitTest.Program.puml
!include .\/Catalyst.Node.Core.UnitTests/obj/Debug/netcoreapp2.1/Catalyst.Node.Core.UnitTest.AssemblyInfo.puml
!include .\/Catalyst.Node.Core.UnitTests/obj/Debug/netcoreapp2.2/Catalyst.Node.Core.UnitTest.Program.puml
!include .\/Catalyst.Node.Core.UnitTests/obj/Debug/netcoreapp2.2/Catalyst.Node.Core.UnitTest.AssemblyInfo.puml
!include .\/Catalyst.Node.Common.UnitTests/obj/Debug/netcoreapp2.1/Catalyst.Node.Common.UnitTests.Program.puml
!include .\/Catalyst.Node.Common.UnitTests/obj/Debug/netcoreapp2.1/Catalyst.Node.Common.UnitTests.AssemblyInfo.puml
!include .\/Catalyst.Node.Common.UnitTests/obj/Debug/netcoreapp2.2/Catalyst.Node.Common.UnitTests.Program.puml
!include .\/Catalyst.Node.Common.UnitTests/obj/Debug/netcoreapp2.2/Catalyst.Node.Common.UnitTests.AssemblyInfo.puml
!include .\/Catalyst.Node.Common/Interfaces/Modules/Ledger/ILedger.puml
!include .\/Catalyst.Node.Common/Interfaces/Modules/Consensus/IConsensus.puml
!include .\/Catalyst.Node.Common/Interfaces/Modules/Dfs/IDfs.puml
!include .\/Catalyst.Node.Common/Interfaces/Modules/KeySigner/IKeySigner.puml
!include .\/Catalyst.Node.Common/Interfaces/Modules/Mempool/IMempool.puml
!include .\/Catalyst.Node.Common/Interfaces/Modules/Contract/IContract.puml
!include .\/Catalyst.Node.Common/obj/Debug/netcoreapp2.1/Catalyst.Node.Common.AssemblyInfo.puml
!include .\/Catalyst.Node.Common/obj/Debug/netcoreapp2.2/Catalyst.Node.Common.AssemblyInfo.puml
!include .\/Catalyst.Node.Common/Helpers/IO/Inbound/AbstractServer.puml
!include .\/Catalyst.Node.Common/Helpers/IO/Inbound/InboundChannelInitializer.puml
!include .\/Catalyst.Node.Common/Helpers/IO/Inbound/TcpServer.puml
!include .\/Catalyst.Node.Common/Helpers/IO/Inbound/UdpServer.puml
!include .\/Catalyst.Node.Common/Helpers/IO/Outbound/UdpClient.puml
!include .\/Catalyst.Node.Common/Helpers/IO/Outbound/TcpClient.puml
!include .\/Catalyst.Node.Common/Helpers/IO/Outbound/OutboundChannelInitializer.puml
!include .\/Catalyst.Node.Common/Helpers/IO/Outbound/AbstractClient.puml
!include .\/Catalyst.Node.Core/obj/Debug/netcoreapp2.1/Catalyst.Node.Core.AssemblyInfo.puml
!include .\/Catalyst.Node.Core/obj/Debug/netcoreapp2.2/Catalyst.Node.Core.AssemblyInfo.puml
@enduml
