@startuml
!include .\/Catalyst.Common.UnitTests/LicenseHeaderTests.puml
!include .\/Catalyst.Common.UnitTests/ProtobufExtensionsTests.puml
!include .\/Catalyst.Cli.UnitTests/SignMessageResponseHandlerTest.puml
!include .\/Catalyst.Cli.UnitTests/VerifyMessageResponseHandlerTest.puml
!include .\/Catalyst.Cli.UnitTests/GetInfoResponseHandlerTest.puml
!include .\/Catalyst.Cli.UnitTests/GetMempoolResponseHandlerTest.puml
!include .\/Catalyst.Cli.UnitTests/CliCommandsTest.puml
!include .\/Catalyst.Cli.UnitTests/GetVersionResponseHandlerTest.puml
!include .\/Catalyst.Cli/Shell.puml
!include .\/Catalyst.Cli/CliConfigCopier.puml
!include .\/Catalyst.Cli/Options.puml
!include .\/Catalyst.Cli/CatalystCli.puml
!include .\/Catalyst.Cli/Program.puml
!include .\/Catalyst.Node.Core/CataystNode.puml
!include .\/Catalyst.Node.Core/Program.puml
!include .\/Catalyst.Common.UnitTests/Keystore/LocalKeyStoreTests.puml
!include .\/Catalyst.Common.UnitTests/Cryptography/CertificateStoreTests.puml
!include .\/Catalyst.Common.UnitTests/Cryptography/CryptographyTests.puml
!include .\/Catalyst.Common.UnitTests/Network/DnsUnitTests.puml
!include .\/Catalyst.Common.UnitTests/Network/IpTests.puml
!include .\/Catalyst.Common.UnitTests/IO/SocketClientRegistryTests.puml
!include .\/Catalyst.Common.UnitTests/Extensions/EnumerableExtensionTests.puml
!include .\/Catalyst.Common.UnitTests/P2P/NetworkTests.puml
!include .\/Catalyst.Common.UnitTests/Modules/ModuleNamesTests.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/TransactionHelper.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/AnyObserver.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/PeerIdentifierHelper.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/MessageStreamHelper.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/PeerIdHelper.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/ConfigFileBasedTest.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/TestPasswordReader.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/FileSystemBasedTest.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/MockQueryResponse.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/TestCertificateStore.puml
!include .\/Catalyst.Common.UnitTests/TestUtils/Traits.puml
!include .\/Catalyst.Cli.UnitTests/TestUtils/ConfigFileBasedTest.puml
!include .\/Catalyst.Cli/Rpc/NodeRpcClientFactory.puml
!include .\/Catalyst.Cli/Rpc/NodeRpcClient.puml
!include .\/Catalyst.Cli/Rpc/NodeRpcConfig.puml
!include .\/Catalyst.Cli/Handlers/GetInfoResponseRequestHandler.puml
!include .\/Catalyst.Cli/Handlers/GetMempoolResponseHandler.puml
!include .\/Catalyst.Cli/Handlers/VerifyMessageResponseHandler.puml
!include .\/Catalyst.Cli/Handlers/GetVersionResponseHandler.puml
!include .\/Catalyst.Cli/Handlers/SignMessageResponseHandler.puml
!include .\/Catalyst.Node.Core.UnitTests/Config/NetworkConfigTests.puml
!include .\/Catalyst.Node.Core.UnitTests/Config/ConfigCopierTests.puml
!include .\/Catalyst.Node.Core.UnitTests/Config/ComponentsConfigTests.puml
!include .\/Catalyst.Node.Core.UnitTests/P2P/P2PMessageFactoryTests.puml
!include .\/Catalyst.Node.Core.UnitTests/P2P/P2PServiceTests.puml
!include .\/Catalyst.Node.Core.UnitTests/P2P/MessageDtoTests.puml
!include .\/Catalyst.Node.Core.UnitTests/P2P/PeerIdentifierTests.puml
!include .\/Catalyst.Node.Core.UnitTests/P2P/PeerDiscoveryUnitTest.puml
!include .\/Catalyst.Node.Core.UnitTests/P2P/MessageCorrelationCacheIntegrationTests.puml
!include .\/Catalyst.Node.Core.UnitTests/P2P/MessageCorrelationCacheTests.puml
!include .\/Catalyst.Node.Core.UnitTests/RPC/SignMessageRequestHandlerTest.puml
!include .\/Catalyst.Node.Core.UnitTests/RPC/RpcIntegrationTests.puml
!include .\/Catalyst.Node.Core.UnitTests/RPC/VerifyMessageRequestHandlerTest.puml
!include .\/Catalyst.Node.Core.UnitTests/Modules/JsonConfiguredModuleTest.puml
!include .\/Catalyst.Node.Core.UnitTests/TestUtils/SocketPortHelper.puml
!include .\/Catalyst.Common/Keystore/LocalKeyStore.puml
!include .\/Catalyst.Common/Keystore/RemoteKeyStore.puml
!include .\/Catalyst.Common/Keystore/KeyStoreServiceWrapped.puml
!include .\/Catalyst.Common/Util/StringUtil.puml
!include .\/Catalyst.Common/Util/NodeUtil.puml
!include .\/Catalyst.Common/Util/ConsoleProgram.puml
!include .\/Catalyst.Common/Util/ByteUtil.puml
!include .\/Catalyst.Common/Util/DateTimeUtil.puml
!include .\/Catalyst.Common/Util/NullObjects.puml
!include .\/Catalyst.Common/Config/P2PMessages.puml
!include .\/Catalyst.Common/Config/Constants.puml
!include .\/Catalyst.Common/Config/IoClients.puml
!include .\/Catalyst.Common/Config/ConfigCopier.puml
!include .\/Catalyst.Common/Config/RpcMessages.puml
!include .\/Catalyst.Common/Config/Network.puml
!include .\/Catalyst.Common/Config/ConfigValueParser.puml
!include .\/Catalyst.Common/Cryptography/CertificateStore.puml
!include .\/Catalyst.Common/Cryptography/NSecCryptoContext.puml
!include .\/Catalyst.Common/Cryptography/NSecPublicKeyWrapper.puml
!include .\/Catalyst.Common/Cryptography/ConsolePasswordReader.puml
!include .\/Catalyst.Common/Cryptography/NSecPrivateKeyWrapper.puml
!include .\/Catalyst.Common/Cryptography/Signature.puml
!include .\/Catalyst.Common/Shell/ShellBase.puml
!include .\/Catalyst.Common/Shell/ConsoleUserOutput.puml
!include .\/Catalyst.Common/Network/EndpointBuilder.puml
!include .\/Catalyst.Common/Network/DevDnsQueryResponse.puml
!include .\/Catalyst.Common/Network/Dns.puml
!include .\/Catalyst.Common/Network/DevDns.puml
!include .\/Catalyst.Common/Network/InjectableLookupClient.puml
!include .\/Catalyst.Common/Network/Ip.puml
!include .\/Catalyst.Common/IO/ChannelInitializerBase.puml
!include .\/Catalyst.Common/IO/Bootstrap.puml
!include .\/Catalyst.Common/IO/IoBase.puml
!include .\/Catalyst.Common/IO/SocketClientRegistry.puml
!include .\/Catalyst.Common/FileSystem/FileSystem.puml
!include .\/Catalyst.Common/Extensions/StringExtensions.puml
!include .\/Catalyst.Common/Extensions/ProtobufExtensions.puml
!include .\/Catalyst.Common/Extensions/StreamExtensions.puml
!include .\/Catalyst.Common/Extensions/EnumerableExtensions.puml
!include .\/Catalyst.Common/Extensions/DatagramExtensions.puml
!include .\/Catalyst.Common/P2P/Peer.puml
!include .\/Catalyst.Common/P2P/PeerIdentifier.puml
!include .\/Catalyst.Common/Rpc/RpcCorrelationCacheBase.puml
!include .\/Catalyst.Common/Modules/ModuleNames.puml
!include .\/Catalyst.Common/Enumerator/Enumeration.puml
!include .\/Catalyst.Common/Interfaces/ICatalystNode.puml
!include .\/Catalyst.Node.Core/Config/Constants.puml
!include .\/Catalyst.Node.Core/P2P/PeerSettings.puml
!include .\/Catalyst.Node.Core/P2P/PeerReputationChange.puml
!include .\/Catalyst.Node.Core/P2P/PeerDiscovery.puml
!include .\/Catalyst.Node.Core/P2P/P2PService.puml
!include .\/Catalyst.Node.Core/P2P/PeerClient.puml
!include .\/Catalyst.Node.Core/RPC/RpcServerSettings.puml
!include .\/Catalyst.Node.Core/RPC/NodeRpcServer.puml
!include .\/Catalyst.Node.Core/Modules/JsonConfiguredModule.puml
!include .\/Catalyst.Node.Core.UnitTests/Modules/Dfs/IpfsEngineTests.puml
!include .\/Catalyst.Node.Core.UnitTests/Modules/Dfs/IpfsDfsTests.puml
!include .\/Catalyst.Node.Core.UnitTests/Modules/Mempool/MempoolTests.puml
!include .\/Catalyst.Node.Core.UnitTests/Modules/Mempool/MempoolIntegrationTests.puml
!include .\/Catalyst.Common/IO/Inbound/AnyTypeSignedServerHandlerBase.puml
!include .\/Catalyst.Common/IO/Inbound/ChanneledAnySigned.puml
!include .\/Catalyst.Common/IO/Inbound/UdpServer.puml
!include .\/Catalyst.Common/IO/Inbound/ServerBootstrap.puml
!include .\/Catalyst.Common/IO/Inbound/InboundChannelInitializerBase.puml
!include .\/Catalyst.Common/IO/Inbound/TcpServer.puml
!include .\/Catalyst.Common/IO/Outbound/Client.puml
!include .\/Catalyst.Common/IO/Outbound/OutboundChannelInitializerBase.puml
!include .\/Catalyst.Common/IO/Outbound/PendingRequest.puml
!include .\/Catalyst.Common/IO/Outbound/UdpClient.puml
!include .\/Catalyst.Common/IO/Outbound/AnySignedTypeClientHandlerBase.puml
!include .\/Catalyst.Common/IO/Outbound/TcpClient.puml
!include .\/Catalyst.Common/IO/Messaging/ProtoDatagramChannelHandlerBase.puml
!include .\/Catalyst.Common/IO/Messaging/MessageHandlerBase.puml
!include .\/Catalyst.Common/IO/Messaging/MessageCorrelationCacheBase.puml
!include .\/Catalyst.Common/IO/Messaging/MessageFactoryBase.puml
!include .\/Catalyst.Common/Modules/KeySigner/KeySigner.puml
!include .\/Catalyst.Common/Interfaces/Keystore/IKeyStoreWrapper.puml
!include .\/Catalyst.Common/Interfaces/Keystore/IKeystore.puml
!include .\/Catalyst.Common/Interfaces/Cryptography/ICertificateStore.puml
!include .\/Catalyst.Common/Interfaces/Cryptography/IPublicKey.puml
!include .\/Catalyst.Common/Interfaces/Cryptography/ICryptoContext.puml
!include .\/Catalyst.Common/Interfaces/Cryptography/IPrivateKey.puml
!include .\/Catalyst.Common/Interfaces/Cryptography/IPasswordReader.puml
!include .\/Catalyst.Common/Interfaces/Network/IDns.puml
!include .\/Catalyst.Common/Interfaces/IO/ISocketClientRegistry.puml
!include .\/Catalyst.Common/Interfaces/IO/ITcpServer.puml
!include .\/Catalyst.Common/Interfaces/IO/ISocketServer.puml
!include .\/Catalyst.Common/Interfaces/IO/ITcpClient.puml
!include .\/Catalyst.Common/Interfaces/IO/IServerBootstrap.puml
!include .\/Catalyst.Common/Interfaces/IO/IUdpClient.puml
!include .\/Catalyst.Common/Interfaces/IO/IBootstrap.puml
!include .\/Catalyst.Common/Interfaces/IO/ISocket.puml
!include .\/Catalyst.Common/Interfaces/IO/IUdpServer.puml
!include .\/Catalyst.Common/Interfaces/FileSystem/IFileSystem.puml
!include .\/Catalyst.Common/Interfaces/Cli/IUserOutput.puml
!include .\/Catalyst.Common/Interfaces/Cli/ICatalystCli.puml
!include .\/Catalyst.Common/Interfaces/Cli/IShell.puml
!include .\/Catalyst.Common/Interfaces/Cli/IAdvancedShell.puml
!include .\/Catalyst.Common/Interfaces/P2P/IPeer.puml
!include .\/Catalyst.Common/Interfaces/P2P/IPeerSettings.puml
!include .\/Catalyst.Common/Interfaces/P2P/IPeerIdentifier.puml
!include .\/Catalyst.Common/Interfaces/P2P/IPeerReputationChange.puml
!include .\/Catalyst.Common/Interfaces/P2P/IPeerDiscovery.puml
!include .\/Catalyst.Common/Interfaces/P2P/IP2PService.puml
!include .\/Catalyst.Common/Interfaces/P2P/IPeerClient.puml
!include .\/Catalyst.Common/Interfaces/P2P/IP2PMessageDto.puml
!include .\/Catalyst.Common/Interfaces/P2P/IReputationManager.puml
!include .\/Catalyst.Common/Interfaces/Rpc/IRpcNodeConfig.puml
!include .\/Catalyst.Common/Interfaces/Rpc/IRpcNodesSettings.puml
!include .\/Catalyst.Common/Interfaces/Rpc/INodeRpcClient.puml
!include .\/Catalyst.Common/Interfaces/Rpc/IRpcNode.puml
!include .\/Catalyst.Common/Interfaces/Rpc/INodeRpcClientFactory.puml
!include .\/Catalyst.Common/Interfaces/Rpc/IRpcServerSettings.puml
!include .\/Catalyst.Common/Interfaces/Rpc/INodeRpcServer.puml
!include .\/Catalyst.Node.Core/P2P/Messaging/P2PCorrelationCache.puml
!include .\/Catalyst.Node.Core/P2P/Messaging/P2PMessageDto.puml
!include .\/Catalyst.Node.Core/P2P/Messaging/P2PMessageFactoryBase.puml
!include .\/Catalyst.Node.Core/RPC/Messaging/RpcMessageFactoryBase.puml
!include .\/Catalyst.Node.Core/RPC/Handlers/GetVersionRequestHandler.puml
!include .\/Catalyst.Node.Core/RPC/Handlers/GetMempoolRequestHandler.puml
!include .\/Catalyst.Node.Core/RPC/Handlers/SignMessageRequestHandler.puml
!include .\/Catalyst.Node.Core/RPC/Handlers/VerifyMessageRequestHandler.puml
!include .\/Catalyst.Node.Core/RPC/Handlers/GetInfoRequestHandler.puml
!include .\/Catalyst.Node.Core/Modules/Consensus/Consensus.puml
!include .\/Catalyst.Node.Core/Modules/Ledger/Ledger.puml
!include .\/Catalyst.Node.Core/Modules/Contract/Contract.puml
!include .\/Catalyst.Node.Core/Modules/Dfs/IIpfsEngine.puml
!include .\/Catalyst.Node.Core/Modules/Dfs/IpfsEngine.puml
!include .\/Catalyst.Node.Core/Modules/Dfs/IpfsDfs.puml
!include .\/Catalyst.Node.Core/Modules/Mempool/Mempool.puml
!include .\/Catalyst.Common.UnitTests/obj/Debug/netcoreapp2.2/Catalyst.Common.UnitTests.AssemblyInfo.puml
!include .\/Catalyst.Node.Common/obj/Debug/netcoreapp2.2/Catalyst.Node.Common.AssemblyInfo.puml
!include .\/Catalyst.Node.Common.UnitTests/obj/Debug/netcoreapp2.2/Catalyst.Node.Common.UnitTests.AssemblyInfo.puml
!include .\/Catalyst.Cli.UnitTests/obj/Debug/netcoreapp2.2/Catalyst.Cli.UnitTests.AssemblyInfo.puml
!include .\/Catalyst.Cli/obj/Debug/netcoreapp2.2/Catalyst.Cli.AssemblyInfo.puml
!include .\/Catalyst.Node.Core.UnitTests/obj/Debug/netcoreapp2.2/Catalyst.Node.Core.UnitTest.AssemblyInfo.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/CommonGrpc.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/Transaction.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/TransactionGrpc.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/RpcGrpc.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/IPPNGrpc.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/DeltaGrpc.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/Catalyst.Common.AssemblyInfo.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/IPPN.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/Rpc.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/Common.puml
!include .\/Catalyst.Common/obj/Debug/netcoreapp2.2/Delta.puml
!include .\/Catalyst.Common/IO/Messaging/Handlers/ReputableAskRequestHandlerBase.puml
!include .\/Catalyst.Common/IO/Messaging/Handlers/CorrelatableMessageHandlerBase.puml
!include .\/Catalyst.Common/IO/Messaging/Handlers/ObservableHandlerBase.puml
!include .\/Catalyst.Common/IO/Messaging/Handlers/ReputableTellResponseHandlerBase.puml
!include .\/Catalyst.Common/Interfaces/IO/Inbound/IChanneledMessage.puml
!include .\/Catalyst.Common/Interfaces/IO/Inbound/ITcpServer.puml
!include .\/Catalyst.Common/Interfaces/IO/Inbound/ISocketServer.puml
!include .\/Catalyst.Common/Interfaces/IO/Inbound/IServerBootstrap.puml
!include .\/Catalyst.Common/Interfaces/IO/Inbound/IUdpServer.puml
!include .\/Catalyst.Common/Interfaces/IO/Outbound/ISocketClient.puml
!include .\/Catalyst.Common/Interfaces/IO/Outbound/ITcpClient.puml
!include .\/Catalyst.Common/Interfaces/IO/Outbound/IUdpClient.puml
!include .\/Catalyst.Common/Interfaces/IO/Messaging/IMessageCorrelationCache.puml
!include .\/Catalyst.Common/Interfaces/IO/Messaging/IReputableCache.puml
!include .\/Catalyst.Common/Interfaces/IO/Messaging/IEnumerableMessageType.puml
!include .\/Catalyst.Common/Interfaces/IO/Messaging/IChanneledMessageStreamer.puml
!include .\/Catalyst.Common/Interfaces/IO/Messaging/IMessageHandler.puml
!include .\/Catalyst.Common/Interfaces/P2P/Messaging/IReputationAskHandler.puml
!include .\/Catalyst.Common/Interfaces/P2P/Messaging/IMessageDto.puml
!include .\/Catalyst.Common/Interfaces/Modules/Consensus/IConsensus.puml
!include .\/Catalyst.Common/Interfaces/Modules/Ledger/ILedger.puml
!include .\/Catalyst.Common/Interfaces/Modules/Contract/IContract.puml
!include .\/Catalyst.Common/Interfaces/Modules/Dfs/IDfs.puml
!include .\/Catalyst.Common/Interfaces/Modules/Mempool/IMempool.puml
!include .\/Catalyst.Common/Interfaces/Modules/KeySigner/IKeySigner.puml
!include .\/Catalyst.Node.Core/obj/Debug/netcoreapp2.2/Catalyst.Node.Core.AssemblyInfo.puml
!include .\/Catalyst.Node.Core/P2P/Messaging/Handlers/GetNeighbourRequestHandler.puml
!include .\/Catalyst.Node.Core/P2P/Messaging/Handlers/TransactionRequestHandler.puml
!include .\/Catalyst.Node.Core/P2P/Messaging/Handlers/PingResponseHandler.puml
!include .\/Catalyst.Node.Core/P2P/Messaging/Handlers/PingRequestAskHandler.puml
@enduml
