@startuml
abstract class "AbstractClient`1"<T> {
    # <<internal>> AbstractClient(logger:ILogger)
    + <<async>> ConnectClient(listenAddress:IPAddress, port:int) : Task<AbstractClient<T>>
}
class "AbstractIo`1"<T> {
}
"AbstractIo`1" "<T>" <|-- "AbstractClient`1"
"AbstractClient`1" --> "Client" IBootstrap
@enduml
