@startuml
abstract class "AbstractClient`2"<T,W> {
    # <<internal>> AbstractClient(logger:ILogger)
    + <<async>> ConnectClient(listenAddress:IPAddress, port:int) : Task<AbstractClient<T, W>>
}
class "AbstractIo`2"<T1,T2> {
}
"AbstractIo`2" "<T,W>" <|-- "AbstractClient`2"
"AbstractClient`2" --> "Client" IBootstrap
@enduml
