@startuml
class TcpClient <<sealed>> {
    + TcpClient(logger:ILogger)
    + Bootstrap(channelInitializer:IChannelHandler) : TcpClient
    + <<override>> ToString() : string
}
class "AbstractClient`1"<T> {
}
"AbstractClient`1" "<ISocketClient>" <|-- TcpClient
@enduml
