@startuml
class UdpClient <<sealed>> {
    + UdpClient(logger:ILogger)
    + Bootstrap(channelInitializer:IChannelHandler) : UdpClient
}
class "AbstractClient`2"<T1,T2> {
}
"AbstractClient`2" "<ISocketClient,IBootstrap>" <|-- UdpClient
@enduml
