# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.ssh.shell="bash"

  config.vm.define "node1" do |catalyst-node-ubuntu1604|
  	node1.vm.box = "debian/stretch64"
  end 
  
  config.vm.network "public_network",
  use_dhcp_assigned_default_route: true
   
  config.vm.synced_folder "/srv/Dev/catalyst-node", "/srv"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
	wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
	sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
	wget -q https://packages.microsoft.com/config/debian/9/prod.list
	sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
	sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
	sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
	sudo apt-get update
	sudo apt-get install dotnet-sdk-2.1 openssl dotnet-runtime-deps-2.1 htop lsof git
  SHELL
end
