@startuml
class NodeRpcClient <<sealed>> {
    + NodeRpcClient(certificate:X509Certificate, nodeConfig:IRpcNodeConfig, responseHandlers:IEnumerable<IRpcResponseHandler>)
}
class "TcpClient`1"<T> {
}
class "IObservable`1"<T> {
}
"TcpClient`1" "<TcpSocketChannel>" <|-- NodeRpcClient
INodeRpcClient <|-- NodeRpcClient
NodeRpcClient --> "MessageStream<IChanneledMessage<AnySigned>>" "IObservable`1"
@enduml
