@startuml
class NodeRpcConfig <<sealed>> {
    + {static} BuildRpcNodeSettingList(config:IConfigurationRoot) : IList<IRpcNodeConfig>
    + NodeId : string <<get>> <<set>>
    + Port : int <<get>> <<set>>
    + PfxFileName : string <<get>> <<set>>
    + SslCertPassword : string <<get>> <<set>>
}
IRpcNodeConfig <|-- NodeRpcConfig
NodeRpcConfig --> "HostAddress" IPAddress
@enduml
