@startuml
class PeerClient <<sealed>> {
    + PeerClient(ipEndPoint:IPEndPoint, messageHandlers:IEnumerable<IP2PMessageHandler>)
    + <<async>> SendMessage(datagramPacket:IByteBufferHolder) : Task
}
class "IObservable`1"<T> {
}
UdpClient <|-- PeerClient
IPeerClient <|-- PeerClient
PeerClient --> "MessageStream<IChanneledMessage<AnySigned>>" "IObservable`1"
@enduml
