@startuml
class Peer {
    - Reputation : int <<get>> <<set>>
    + IsAwolBot : bool <<get>>
    + Dispose() : void
    <<internal>> Touch() : void
    + IncreaseReputation() : void
    + DecreaseReputation() : void
    # <<virtual>> Dispose(disposing:bool) : void
}
IDisposable <|-- Peer
Peer o-> "Logger" ILogger
Peer --> "LastSeen" DateTime
Peer --> "EndPoint" IPEndPoint
Peer --> "PeerIdentifier" IPeerIdentifier
Peer --> "InactiveFor" TimeSpan
@enduml
