@startuml
class PeerSettings <<sealed>> {
    + PeerSettings(rootSection:IConfigurationRoot)
    + PayoutAddress : string <<get>> <<set>>
    + PublicKey : string <<get>> <<set>>
    + Announce : bool <<get>> <<set>>
    + MaxConnections : ushort <<get>> <<set>>
    + Port : int <<get>> <<set>>
    + Magic : int <<get>> <<set>>
    + PfxFileName : string <<get>> <<set>>
    + AddressVersion : byte <<get>> <<set>>
}
class "IList`1"<T> {
}
IPeerSettings <|-- PeerSettings
PeerSettings --> "Network" Network
PeerSettings --> "AnnounceServer" IPEndPoint
PeerSettings --> "EndPoint" IPEndPoint
PeerSettings --> "BindAddress" IPAddress
PeerSettings --> "KnownNodes<string>" "IList`1"
PeerSettings --> "SeedServers<string>" "IList`1"
@enduml
