### YamlMime:ManagedReference
items:
- uid: Catalyst.Core.Lib.Config
  commentId: N:Catalyst.Core.Lib.Config
  id: Catalyst.Core.Lib.Config
  children:
  - Catalyst.Core.Lib.Config.ConfigCopier
  - Catalyst.Core.Lib.Config.ConfigValueParser
  - Catalyst.Core.Lib.Config.Constants
  langs:
  - csharp
  - vb
  name: Catalyst.Core.Lib.Config
  nameWithType: Catalyst.Core.Lib.Config
  fullName: Catalyst.Core.Lib.Config
  type: Namespace
  assemblies:
  - Catalyst.Core.Lib
references:
- uid: Catalyst.Core.Lib.Config.ConfigCopier
  commentId: T:Catalyst.Core.Lib.Config.ConfigCopier
  name: ConfigCopier
  nameWithType: ConfigCopier
  fullName: Catalyst.Core.Lib.Config.ConfigCopier
- uid: Catalyst.Core.Lib.Config.ConfigValueParser
  commentId: T:Catalyst.Core.Lib.Config.ConfigValueParser
  name: ConfigValueParser
  nameWithType: ConfigValueParser
  fullName: Catalyst.Core.Lib.Config.ConfigValueParser
- uid: Catalyst.Core.Lib.Config.Constants
  commentId: T:Catalyst.Core.Lib.Config.Constants
  name: Constants
  nameWithType: Constants
  fullName: Catalyst.Core.Lib.Config.Constants
