@startuml
class Mempool <<sealed>> {
    + Mempool(transactionStore:IRepository<Transaction, TransactionSignature>, logger:ILogger)
    + GetMemPoolContent() : IEnumerable<Transaction>
    + GetMemPoolContentEncoded() : List<byte[]>
    + GetTransaction(key:TransactionSignature) : Transaction
    + SaveTransaction(transaction:Transaction) : bool
}
class "IRepository`2"<T1,T2> {
}
IMempool <|-- Mempool
Mempool --> "_logger" ILogger
Mempool --> "_transactionStore<Transaction,TransactionSignature>" "IRepository`2"
@enduml
