@startuml
class ComponentsConfigTests <<sealed>> {
    - <<readonly>> _componentsConfig : string
    - <<const>> PeerMiniConfigFile : string = "peerConfigSection.json"
    - <<const>> PublicKeyAsString : string = "302a300506032b65700321001783421742816abf"
    + ComponentsConfigTests()
    - {static} ConfigureAndBuildContainer(configFiles:string[]) : IContainer
    + Components_config_should_allow_resolving_IPeerSettings() : void
    + Components_config_should_allow_resolving_IPeerIdentifier() : void
    + Components_config_should_allow_resolving_Collection_of_MessageHandlers() : void
}
@enduml
