@startuml
class ProtoDatagramChannelHandlerBase <<sealed>> {
    # <<override>> ChannelRead0(context:IChannelHandlerContext, packet:DatagramPacket) : void
    + <<override>> ExceptionCaught(context:IChannelHandlerContext, e:Exception) : void
}
class "ObservableHandlerBase`1"<T> {
}
"ObservableHandlerBase`1" "<DatagramPacket>" <|-- ProtoDatagramChannelHandlerBase
ProtoDatagramChannelHandlerBase o-> "Logger" ILogger
@enduml
