@startuml
class Enumeration {
    # Enumeration(id:int, name:string)
    + Name : string <<get>>
    - Id : int <<get>>
    + <<override>> ToString() : string
    + {static} TryParse(value:string, parsed:T, comparison:StringComparison) : bool
    + {static} Parse(value:string, comparison:StringComparison) : T
    + {static} GetAll() : IEnumerable<T>
    + Equals(other:Enumeration) : bool
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<Enumeration>" <|-- Enumeration
@enduml
