@startuml
abstract class FileSystemBasedTest {
    # <<readonly>> _currentTestName : string
    # FileSystemBasedTest(output:ITestOutputHelper)
    + Dispose() : void
    # <<virtual>> Dispose(disposing:bool) : void
    - {static} TryDeleteFolder(d:DirectoryInfo) : void
    + {static} GetHashFromItems(items:IEnumerable<T>) : uint
}
IDisposable <|-- FileSystemBasedTest
FileSystemBasedTest --> "_currentTest" ITest
FileSystemBasedTest --> "_fileSystem" IFileSystem
FileSystemBasedTest --> "_output" ITestOutputHelper
FileSystemBasedTest --> "_testDirectory" DirectoryInfo
@enduml
