@startuml
class IpfsEngine <<sealed>> {
    + {static} <<readonly>> KeyChainDefaultKeyType : string = "ed25519"
    {static} IpfsEngine()
    + IpfsEngine(passwordReader:IPasswordReader, peerSettings:IPeerSettings, fileSystem:IFileSystem, logger:ILogger)
    + <<async>> StartAsync() : Task
    + <<async>> StopAsync() : Task
    - Dispose(disposing:bool) : void
    + Dispose() : void
}
IIpfsEngine <|-- IpfsEngine
IpfsEngine --> "_passphrase" SecureString
IpfsEngine --> "Bitswap" IBitswapApi
IpfsEngine --> "Block" IBlockApi
IpfsEngine --> "Bootstrap" IBootstrapApi
IpfsEngine --> "Config" IConfigApi
IpfsEngine --> "Dag" IDagApi
IpfsEngine --> "Dht" IDhtApi
IpfsEngine --> "Dns" IDnsApi
IpfsEngine --> "FileSystem" IFileSystemApi
IpfsEngine --> "Generic" IGenericApi
IpfsEngine --> "Key" IKeyApi
IpfsEngine --> "Name" INameApi
IpfsEngine --> "Object" IObjectApi
IpfsEngine --> "Pin" IPinApi
IpfsEngine --> "PubSub" IPubSubApi
IpfsEngine --> "Stats" IStatsApi
IpfsEngine --> "Swarm" ISwarmApi
IpfsEngine --> "Options" IpfsEngineOptions
@enduml
