@startuml
class MempoolIntegrationTests <<sealed>> {
    + MempoolIntegrationTests(output:ITestOutputHelper)
    - <<async>> Mempool_can_save_and_retrieve(mempoolModuleFile:FileInfo) : Task
    - <<async>> CreateAlteredConfigForMempool(mempoolConfigFile:FileInfo) : Task<string>
    - <<async>> PointXmlConfigToLocalTestFolder(mempoolConfigFile:string) : Task<string>
    + <<async>> Mempool_with_InMemoryRepo_can_save_and_retrieve() : Task
    + <<async>> Mempool_with_XmlRepo_can_save_and_retrieve() : Task
}
ConfigFileBasedTest <|-- MempoolIntegrationTests
@enduml
