@startuml
class AnyTypeSignedServerHandlerBase <<sealed>> {
    + <<override>> IsSharable : bool <<get>>
    # <<override>> ChannelRead0(ctx:IChannelHandlerContext, msg:AnySigned) : void
    + <<override>> ChannelReadComplete(ctx:IChannelHandlerContext) : void
    + <<override>> ExceptionCaught(ctx:IChannelHandlerContext, e:Exception) : void
}
class "ObservableHandlerBase`1"<T> {
}
"ObservableHandlerBase`1" "<AnySigned>" <|-- AnyTypeSignedServerHandlerBase
AnyTypeSignedServerHandlerBase o-> "Logger" ILogger
@enduml
