@startuml
class RpcIntegrationTests <<sealed>> {
    - <<const>> MaxWaitInMs : int = 1000
    + RpcIntegrationTests(output:ITestOutputHelper)
    + ServerConnectedToCorrectPort() : void
    + RpcServer_Can_Handle_GetInfoRequest() : void
    + RpcServer_Can_Handle_GetVersionRequest() : void
    + RpcServer_Can_Handle_GetMempoolRequest() : void
    + RpcServer_Can_Handle_SignMessageRequest() : void
}
ConfigFileBasedTest <|-- RpcIntegrationTests
RpcIntegrationTests --> "_config" IConfigurationRoot
@enduml
