@startuml
class GetInfoResponseHandlerTest <<sealed>> {
    {static} GetInfoResponseHandlerTest()
    + GetInfoResponseHandlerTest()
    - CreateStreamWithMessage(response:AnySigned) : IObservable<ChanneledAnySigned>
    + RpcClient_Can_Handle_GetInfoResponse(query:string) : void
    + Dispose() : void
}
class "List`1"<T> {
}
IDisposable <|-- GetInfoResponseHandlerTest
GetInfoResponseHandlerTest --> "_logger" ILogger
GetInfoResponseHandlerTest --> "_requestHandler" GetInfoResponseHandler
GetInfoResponseHandlerTest --> "QueryContents<object[]>" "List`1"
GetInfoResponseHandlerTest --> "_fakeContext" IChannelHandlerContext
GetInfoResponseHandlerTest --> "_output" IUserOutput
@enduml
