@startuml
class GetMempoolResponseHandlerTest <<sealed>> {
    {static} GetMempoolResponseHandlerTest()
    + GetMempoolResponseHandlerTest()
    - CreateStreamWithMessage(response:AnySigned) : IObservable<ChanneledAnySigned>
    + {static} CreateMemPoolData() : MapField<string, string>
    + RpcClient_Can_Handle_GetMempoolResponse(memPoolMap:MapField<string, string>) : void
    + Dispose() : void
}
class "List`1"<T> {
}
IDisposable <|-- GetMempoolResponseHandlerTest
GetMempoolResponseHandlerTest --> "_logger" ILogger
GetMempoolResponseHandlerTest --> "_fakeContext" IChannelHandlerContext
GetMempoolResponseHandlerTest --> "QueryContents<object[]>" "List`1"
GetMempoolResponseHandlerTest --> "_output" IUserOutput
GetMempoolResponseHandlerTest --> "_handler" GetMempoolResponseHandler
@enduml
