@startuml
class GetVersionResponseHandlerTest <<sealed>> {
    {static} GetVersionResponseHandlerTest()
    + GetVersionResponseHandlerTest()
    - CreateStreamWithMessage(response:AnySigned) : IObservable<ChanneledAnySigned>
    + RpcClient_Can_Handle_GetVersionResponse(version:string) : void
    + Dispose() : void
}
class "List`1"<T> {
}
IDisposable <|-- GetVersionResponseHandlerTest
GetVersionResponseHandlerTest --> "_output" IUserOutput
GetVersionResponseHandlerTest --> "QueryContents<object[]>" "List`1"
GetVersionResponseHandlerTest --> "_fakeContext" IChannelHandlerContext
GetVersionResponseHandlerTest --> "_logger" ILogger
GetVersionResponseHandlerTest --> "_handler" GetVersionResponseHandler
@enduml
