@startuml
abstract class ShellBase {
    # ShellBase()
    - Prompt : string <<get>>
    - ServiceName : string <<get>>
    + {abstract} OnStart(args:string[]) : bool
    + {abstract} OnStartWork(args:string[]) : bool
    + {abstract} OnStop(args:string[]) : bool
    + {abstract} OnStopNode(args:string[]) : bool
    + {abstract} OnStopWork(args:string[]) : bool
    # OnHelpCommand(advancedCmds:string) : bool
    # <<virtual>> OnCommand(args:string[]) : bool
    - OnGetCommand(args:string[]) : bool
    # {abstract} OnGetInfo() : bool
    # {abstract} OnGetConfig() : bool
    # {abstract} OnGetVersion() : bool
    # {abstract} OnGetMempool() : bool
    - ParseCmdArgs(args:string[], regExPattern:string) : string
    + {static} ReadPassword(prompt:string) : string
    - {static} ShellLogKey(key:ConsoleKeyInfo) : void
    + {static} ReadSecureString(prompt:string) : SecureString
    + RunConsole() : bool
    # {static} CommandNotFound(args:string[]) : bool
}
IShell <|-- ShellBase
ShellBase --> "AppCulture" CultureInfo
@enduml
