@startuml
class Shell <<sealed>> {
    + Shell()
    + OnDfsCommand(args:string[]) : bool
    + OnWalletCommand(args:string[]) : bool
    + OnPeerCommand(args:string[]) : bool
    + OnConsensusCommand(args:string[]) : bool
    - OnHelpCommand() : bool
    # <<override>> OnCommand(args:string[]) : bool
    - OnConnectNode(args:string[]) : bool
    + <<override>> OnStart(args:string[]) : bool
    + <<override>> OnStartWork(args:string[]) : bool
    + <<override>> OnStop(args:string[]) : bool
    + <<override>> OnStopNode(args:string[]) : bool
    + <<override>> OnStopWork(args:string[]) : bool
    + OnGetCommand(args:string[]) : bool
    # <<override>> OnGetInfo() : bool
    # <<override>> OnGetVersion() : bool
    # <<override>> OnGetConfig() : bool
    - OnGetDelta(args:string[]) : bool
    # <<override>> OnGetMempool() : bool
    - OnMessageCommand(args:string[]) : bool
}
ShellBase <|-- Shell
IAds <|-- Shell
@enduml
