@startuml
class Program <<static>> {
    - {static} <<readonly>> LifetimeTag : string
    - {static} <<readonly>> LogFileName : string = "Catalyst.Cli..log"
    {static} Program()
    + {static} Main() : int
}
Program --> "_logger" ILogger
Program --> "DeclaringType" Type
@enduml
