@startuml
class GetNeighbourRequestHandler {
    + GetNeighbourRequestHandler(peerIdentifier:IPeerIdentifier, reputableCache:IReputableCache, logger:ILogger)
    # <<override>> Handler(message:IChanneledMessage<AnySigned>) : void
}
class "ReputableAskRequestHandlerBase`2"<T1,T2> {
}
"ReputableAskRequestHandlerBase`2" "<PeerNeighborsRequest,IReputableCache>" <|-- GetNeighbourRequestHandler
IP2PMessageHandler <|-- GetNeighbourRequestHandler
GetNeighbourRequestHandler --> "_peerIdentifier" IPeerIdentifier
@enduml
