@startuml
class TransactionRequestHandler <<sealed>> {
    + TransactionRequestHandler(reputableCache:IReputableCache, logger:ILogger)
    # <<override>> Handler(message:IChanneledMessage<AnySigned>) : void
}
class "ReputableAskRequestHandlerBase`2"<T1,T2> {
}
"ReputableAskRequestHandlerBase`2" "<Transaction,IReputableCache>" <|-- TransactionRequestHandler
IP2PMessageHandler <|-- TransactionRequestHandler
@enduml
