@startuml
class Program <<static>> {
    - {static} <<readonly>> LifetimeTag : string
    - {static} <<readonly>> ExecutionDirectory : string
    {static} Program()
    + {static} Main(args:string[]) : int
    {static} CurrentDomain_ProcessExit(sender:object, e:EventArgs) : void
    + {static} TryLoadAssemblyFromExecutionDirectory(context:AssemblyLoadContext, assemblyName:AssemblyName) : Assembly
    + {static} LogUnhandledException(sender:object, e:UnhandledExceptionEventArgs) : void
}
Program --> "Logger" ILogger
Program --> "_cancellationSource" CancellationTokenSource
@enduml
