@startuml
class IpfsEngineTests <<sealed>> {
    + IpfsEngineTests(output:ITestOutputHelper)
    + Constructor_should_read_seed_servers_addresses_from_peerSettings() : void
    + Constructor_should_throw_when_no_peers_in_peerSettings() : void
    + Constructor_should_read_a_password() : void
    + Constructor_should_use_ipfs_subfolder() : void
    + Constructor_should_use_ipfs_private_network() : void
    # <<override>> Dispose(disposing:bool) : void
}
FileSystemBasedTest <|-- IpfsEngineTests
IpfsEngineTests --> "_peerSettings" IPeerSettings
IpfsEngineTests --> "_passwordReader" IPasswordReader
IpfsEngineTests --> "_logger" ILogger
IpfsEngineTests --> "_ipfsEngine" IpfsEngine
@enduml
