@startuml
class CryptographyTests <<sealed>> {
    + CryptographyTests()
    + TestFailurePrivateKeyImport() : void
    + TestFailurePrivateKeySecondExport() : void
    + TestFailurePublicKeyImport() : void
    + TestFailureSigningVerification() : void
    + TestPrivateKeyExport() : void
    + TestPrivateKeyImportFromExported() : void
    + TestPublicKeyFromPrivateKey() : void
    + TestPublicKeyImport() : void
    + TestSigningVerification() : void
    + TestVerifyWithImportedPublicKey() : void
}
CryptographyTests --> "_context" ICryptoContext
@enduml
