@startuml
class NetworkTests <<static>> {
    {static} NetworkTests()
    + {static} Network_can_be_parsed_from_string(value:string, expectedNetwork:Config.Network) : void
    + {static} All_should_return_all_declared_names() : void
}
class "List`1"<T> {
}
NetworkTests --> "NetworksAndExpectations<object[]>" "List`1"
@enduml
