@startuml
class P2PCorrelationCache <<sealed>> {
    - {static} <<readonly>> BaseReputationChange : int = 1
    + P2PCorrelationCache(cache:IMemoryCache, logger:ILogger, cacheTtl:TimeSpan)
    # <<override>> GetInheritorDelegate() : PostEvictionDelegate
    + ChangeReputationOnEviction(key:object, value:object, reason:EvictionReason, state:object) : void
    + <<override>> TryMatchResponse(response:AnySigned) : TRequest
    # <<override>> Dispose(disposing:bool) : void
}
class "ReplaySubject`1"<T> {
}
class "IObservable`1"<T> {
}
MessageCorrelationCacheBase <|-- P2PCorrelationCache
IReputableCache <|-- P2PCorrelationCache
P2PCorrelationCache --> "_ratingChangeSubject<IPeerReputationChange>" "ReplaySubject`1"
P2PCorrelationCache --> "PeerRatingChanges<IPeerReputationChange>" "IObservable`1"
@enduml
