@startuml
class "P2PMessageDto`2"<TMessage,TMessageType> <<sealed>> {
    + Type : TMessageType <<get>>
    + Message : TMessage <<get>>
    + P2PMessageDto(type:TMessageType, message:TMessage, destination:IPEndPoint, sender:IPeerIdentifier)
}
class "IP2PMessageDto`2"<T1,T2> {
}
"IP2PMessageDto`2" "<TMessage,TMessageType>" <|-- "P2PMessageDto`2"
"P2PMessageDto`2" --> "Recipient" IPEndPoint
"P2PMessageDto`2" --> "Sender" IPeerIdentifier
@enduml
