@startuml
class ConsolePasswordReader {
    + ReadSecurePassword(passwordContext:string) : SecureString
    + ReadSecurePasswordAsChars(passwordContext:string) : char[]
    - {static} ReadCharsFromConsole(passwordContext:string, appendChar:Action<char, int>, removeChar:Action<int>, maxLength:int) : int
}
IPasswordReader <|-- ConsolePasswordReader
@enduml
