@startuml
class NSecCryptoContext <<sealed>> {
    + GeneratePrivateKey() : IPrivateKey
    + ImportPublicKey(blob:ReadOnlySpan<byte>) : IPublicKey
    + ExportPublicKey(key:IPublicKey) : byte[]
    + ImportPrivateKey(blob:ReadOnlySpan<byte>) : IPrivateKey
    + ExportPrivateKey(key:IPrivateKey) : byte[]
    + Sign(privateKey:IPrivateKey, data:ReadOnlySpan<byte>) : byte[]
    + Verify(key:IPublicKey, data:ReadOnlySpan<byte>, signature:ReadOnlySpan<byte>) : bool
    + GetPublicKey(key:IPrivateKey) : IPublicKey
    + AddressFromKey(key:IPublicKey) : string
}
ICryptoContext <|-- NSecCryptoContext
NSecCryptoContext o-> "Algorithm" SignatureAlgorithm
NSecCryptoContext o-> "_publicKeyFormat" KeyBlobFormat
NSecCryptoContext o-> "_privateKeyFormat" KeyBlobFormat
@enduml
