@startuml
interface IShell {
    RunConsole() : bool
    OnStart(args:string[]) : bool
    OnStartWork(args:string[]) : bool
    OnStop(args:string[]) : bool
    OnStopNode(args:string[]) : bool
    OnStopWork(args:string[]) : bool
    OnCommand(args:string[]) : bool
    ParseCommand(args:string[]) : bool
}
@enduml
