@startuml
abstract class "AbstractIo`2"<ST,BT> {
    # <<const>> BackLogValue : int = 100
    # <<internal>> AbstractIo(logger:ILogger)
    + <<virtual>> <<async>> Shutdown() : Task
    + Dispose() : void
    - Dispose(disposing:bool) : void
    + <<override>> ToString() : string
}
"AbstractIo`2" --> "_logger" ILogger
"AbstractIo`2" --> "Channel" IChannel
"AbstractIo`2" --> "WorkerEventLoop" IEventLoopGroup
@enduml
