@startuml
interface "ISocketClientRegistry`1"<TSocketChannel> {
    GenerateClientHashCode(socketEndpoint:IPEndPoint) : int
    AddClientToRegistry(socketHashCode:int, socket:TSocketChannel) : bool
    GetClientFromRegistry(socketHashCode:int) : TSocketChannel
    RemoveClientFromRegistry(socketHashCode:int) : bool
    GetRegistryType() : string
}
class "IDictionary`2"<T1,T2> {
}
"ISocketClientRegistry`1" --> "Registry<int,TSocketChannel>" "IDictionary`2"
@enduml
