@startuml
class AnnounceNodeEventArgs {
    + AnnounceNodeEventArgs(nodeIdentity:IPeerIdentifier)
}
EventArgs <|-- AnnounceNodeEventArgs
AnnounceNodeEventArgs --> "NodeIdentity" IPeerIdentifier
@enduml
