@startuml
class "RpcMessageFactoryBase`2"<TMessage,TMessageType> {
    + <<override>> GetMessage(dto:IP2PMessageDto<TMessage, TMessageType>) : AnySigned
}
class "MessageFactoryBase`2"<T1,T2> {
}
class "IMessage`1"<T> {
}
"MessageFactoryBase`2" "<TMessage,TMessageType>" <|-- "RpcMessageFactoryBase`2"
@enduml
