@startuml
class RedisConnector {
    + RedisConnector(connectionParam:string)
    + Dispose() : void
    # <<virtual>> Dispose(disposing:bool) : void
}
IDisposable <|-- RedisConnector
IRedisConnector <|-- RedisConnector
RedisConnector --> "Connection" IConnectionMultiplexer
RedisConnector --> "Database" IDatabase
@enduml
