@startuml
class DevDnsQueryResponse <<sealed>> {
    + AuditTrail : string <<get>>
    + ErrorMessage : string <<get>>
    + HasError : bool <<get>>
    + MessageSize : int <<get>>
    + {static} BuildDnsResourceRecords(domainName:string, value:string) : List<DnsResourceRecord>
}
class "IReadOnlyList`1"<T> {
}
class "IEnumerable`1"<T> {
}
IDnsQueryResponse <|-- DevDnsQueryResponse
DevDnsQueryResponse --> "Questions<DnsQuestion>" "IReadOnlyList`1"
DevDnsQueryResponse --> "Additionals<DnsResourceRecord>" "IReadOnlyList`1"
DevDnsQueryResponse --> "AllRecords<DnsResourceRecord>" "IEnumerable`1"
DevDnsQueryResponse --> "Answers<DnsResourceRecord>" "IReadOnlyList`1"
DevDnsQueryResponse --> "Authorities<DnsResourceRecord>" "IReadOnlyList`1"
DevDnsQueryResponse --> "Header" DnsResponseHeader
DevDnsQueryResponse --> "NameServer" NameServer
@enduml
