@startuml
class DevDns {
    + DevDns(configurationRoot:IConfigurationRoot)
    + <<async>> GetTxtRecords(hostnames:IList<string>) : Task<IList<IDnsQueryResponse>>
    + <<async>> GetTxtRecords(hostname:string) : Task<IDnsQueryResponse>
}
class "IList`1"<T> {
}
IDns <|-- DevDns
DevDns --> "_seedServers<string>" "IList`1"
DevDns --> "_dnsQueryAnswerValues<IPEndPoint>" "IList`1"
@enduml
