@startuml
class JsonConfiguredModuleTest {
    + JsonConfiguredModuleTest()
    - {static} PerformExtraRegistrations(builder:ContainerBuilder) : void
    - ComponentsJsonFile_should_configure_modules(interfaceType:Type, resolutionType:Type) : void
}
BaseModuleConfigTest <|-- JsonConfiguredModuleTest
@enduml
