@startuml
class LocalKeyStoreTests <<sealed>> {
    - <<readonly>> _fileName : string
    - <<readonly>> _password : string
    + LocalKeyStoreTests(output:ITestOutputHelper)
    + TestStoreAndRetrieveKey() : void
    + TestWrongPasswordStoreAndRetrieveKey() : void
}
FileSystemBasedTest <|-- LocalKeyStoreTests
LocalKeyStoreTests --> "_keystore" IKeyStore
LocalKeyStoreTests --> "_context" ICryptoContext
LocalKeyStoreTests --> "_keyStoreService" IKeyStoreWrapper
LocalKeyStoreTests --> "_privateKey" NSecPrivateKeyWrapper
@enduml
